#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\\n%s\\n\\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path."; exit 2; }
git lfs post-merge "$@"
git rev-parse --quiet --verify "HEAD@{1}" >/dev/null 2>&1 || exit 0
exec "$(dirname "$0")/_rebuild.sh" "HEAD@{1} HEAD"
