// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

namespace McpGeneratedParentSchema
{
void AppendBuildEnvironmentStructures(FMcpSchemaBuilder& Schema)
{
			Schema.Object(TEXT("arriveTangent"), TEXT("Arrive tangent."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("bounds"), TEXT("Procedural foliage bounds {location, size}."), [](FMcpSchemaBuilder& S) {
				  S.Object(TEXT("location"), TEXT("Bounds location."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("x"), TEXT("X"));
				  	  S.Number(TEXT("y"), TEXT("Y"));
				  	  S.Number(TEXT("z"), TEXT("Z"));
				  });
				  S.Object(TEXT("size"), TEXT("Bounds size."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("x"), TEXT("X"));
				  	  S.Number(TEXT("y"), TEXT("Y"));
				  	  S.Number(TEXT("z"), TEXT("Z"));
				  });
			});
			Schema.Object(TEXT("captureOffset"), TEXT("Capture offset."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("componentCount"), TEXT("Component count {x, y}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("direction"), TEXT("Direction rotation."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("pitch"), TEXT("Pitch"));
				  S.Number(TEXT("yaw"), TEXT("Yaw"));
				  S.Number(TEXT("roll"), TEXT("Roll"));
			});
			Schema.ArrayOfObjects(TEXT("foliageTypes"), TEXT("Foliage type specs."), [](FMcpSchemaBuilder& S) {
				  S.String(TEXT("meshPath"), TEXT("Mesh path."));
				  S.Number(TEXT("density"), TEXT("Density."));
			});
			Schema.ArrayOfObjects(TEXT("initialPoints"), TEXT("Initial spline points (alias of points)."), [](FMcpSchemaBuilder& S) {
				  S.Object(TEXT("location"), TEXT("Point location."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("x"), TEXT("X"));
				  	  S.Number(TEXT("y"), TEXT("Y"));
				  	  S.Number(TEXT("z"), TEXT("Z"));
				  });
			});
			Schema.Object(TEXT("leaveTangent"), TEXT("Leave tangent."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("location"), TEXT("World-space location {x, y, z}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.ArrayOfObjects(TEXT("locations"), TEXT("Instance locations."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("pointRotation"), TEXT("Spline point rotation."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("pitch"), TEXT("Pitch"));
				  S.Number(TEXT("yaw"), TEXT("Yaw"));
				  S.Number(TEXT("roll"), TEXT("Roll"));
			});
			Schema.Object(TEXT("pointScale"), TEXT("Spline point scale."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.ArrayOfObjects(TEXT("points"), TEXT("Spline points."), [](FMcpSchemaBuilder& S) {
				  S.Object(TEXT("position"), TEXT("Position."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("x"), TEXT("X"));
				  	  S.Number(TEXT("y"), TEXT("Y"));
				  	  S.Number(TEXT("z"), TEXT("Z"));
				  });
				  S.Object(TEXT("arriveTangent"), TEXT("Arrive tangent."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("x"), TEXT("X"));
				  	  S.Number(TEXT("y"), TEXT("Y"));
				  	  S.Number(TEXT("z"), TEXT("Z"));
				  });
				  S.Object(TEXT("leaveTangent"), TEXT("Leave tangent."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("x"), TEXT("X"));
				  	  S.Number(TEXT("y"), TEXT("Y"));
				  	  S.Number(TEXT("z"), TEXT("Z"));
				  });
				  S.Object(TEXT("rotation"), TEXT("Rotation."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("pitch"), TEXT("Pitch"));
				  	  S.Number(TEXT("yaw"), TEXT("Yaw"));
				  	  S.Number(TEXT("roll"), TEXT("Roll"));
				  });
				  S.Object(TEXT("scale"), TEXT("Scale."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("x"), TEXT("X"));
				  	  S.Number(TEXT("y"), TEXT("Y"));
				  	  S.Number(TEXT("z"), TEXT("Z"));
				  });
			});
			Schema.Object(TEXT("position"), TEXT("Position {x, y, z}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("region"), TEXT("Rectangular region {minX, minY, maxX, maxY}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("minX"), TEXT("Min X."));
				  S.Number(TEXT("minY"), TEXT("Min Y."));
				  S.Number(TEXT("maxX"), TEXT("Max X."));
				  S.Number(TEXT("maxY"), TEXT("Max Y."));
			});
			Schema.Object(TEXT("rotation"), TEXT("Rotation {pitch, yaw, roll}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("pitch"), TEXT("Pitch"));
				  S.Number(TEXT("yaw"), TEXT("Yaw"));
				  S.Number(TEXT("roll"), TEXT("Roll"));
			});
			Schema.ArrayOfObjects(TEXT("transforms"), TEXT("Instance transforms."), [](FMcpSchemaBuilder& S) {
				  S.Object(TEXT("location"), TEXT("Location."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("x"), TEXT("X"));
				  	  S.Number(TEXT("y"), TEXT("Y"));
				  	  S.Number(TEXT("z"), TEXT("Z"));
				  });
				  S.Object(TEXT("rotation"), TEXT("Rotation."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("pitch"), TEXT("Pitch"));
				  	  S.Number(TEXT("yaw"), TEXT("Yaw"));
				  	  S.Number(TEXT("roll"), TEXT("Roll"));
				  });
				  S.Object(TEXT("scale"), TEXT("Scale."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("x"), TEXT("X"));
				  	  S.Number(TEXT("y"), TEXT("Y"));
				  	  S.Number(TEXT("z"), TEXT("Z"));
				  });
			});
}
}
