// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ControlActor : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("control_actor"); }
	FString GetDescription() const override { return TEXT("Spawn actors, set transforms, enable physics, add components, manage tags, and attach actors."); }
	FString GetCategory() const override { return TEXT("core"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("actorClass"), TEXT("Alias of classPath accepted by the spawn handler (normalizeArgs alias)."));
			Schema.String(TEXT("actorName"), TEXT("Target actor name in the current level."));
			Schema.Array(TEXT("actorNames"), TEXT("Actor names to act on (batch delete)."), TEXT("string"));
			Schema.Bool(TEXT("allComponents"), TEXT("When true, apply the material to all mesh components."));
			Schema.AnyValue(TEXT("arguments"), TEXT("Function arguments (any type)."));
			Schema.String(TEXT("blueprintPath"), TEXT("Canonical /Game Blueprint asset path to spawn from."));
			Schema.String(TEXT("childActor"), TEXT("Child actor name to attach."));
			Schema.String(TEXT("class"), TEXT("Unreal class name or path (alias of className)."));
			Schema.String(TEXT("className"), TEXT("Unreal class name or path to find actors by class."));
			Schema.String(TEXT("classPath"), TEXT("Unreal class path (e.g. /Script/Engine.PointLight) for the actor to spawn."));
			Schema.Bool(TEXT("collisionEnabled"), TEXT("Desired collision enabled state."));
			Schema.String(TEXT("componentName"), TEXT("Target component name on the actor."));
			Schema.String(TEXT("componentType"), TEXT("Component class to add."));
			Schema.StringEnum(TEXT("deleteScope"), { TEXT("actors"), TEXT("by_tag") }, TEXT("Which delete variant to run; omit for 'actors'."));
			Schema.StringEnum(TEXT("edit"), { TEXT("add"), TEXT("remove"), TEXT("set_property"), TEXT("set_properties") }, TEXT("Which edit component variant to run."));
			Schema.String(TEXT("filter"), TEXT("Optional name substring filter for list."));
			Schema.StringEnum(TEXT("findBy"), { TEXT("class"), TEXT("name") }, TEXT("Which find variant to run."));
			Schema.Array(TEXT("force"), TEXT("Force vector to apply as [x, y, z]."), TEXT("number"));
			Schema.String(TEXT("functionName"), TEXT("Actor function name to call."));
			Schema.StringEnum(TEXT("info"), { TEXT("components"), TEXT("bounds") }, TEXT("Which get components variant to run; omit for 'components'."));
			Schema.Number(TEXT("limit"), TEXT("Maximum number of actors to return in a list."));
			Schema.Array(TEXT("location"), TEXT("World or relative location as [x, y, z]."), TEXT("number"));
			Schema.Number(TEXT("materialIndex"), TEXT("Alias of materialSlot accepted by the material handlers (normalizeArgs alias)."));
			Schema.String(TEXT("materialPath"), TEXT("Canonical /Game material asset path to apply."));
			Schema.Number(TEXT("materialSlot"), TEXT("Material slot/index to override (0-based)."));
			Schema.String(TEXT("meshPath"), TEXT("Canonical /Game mesh asset path to assign on spawn."));
			Schema.String(TEXT("name"), TEXT("Actor name or search query."));
			Schema.String(TEXT("newName"), TEXT("New name for the duplicate or renamed actor."));
			Schema.Array(TEXT("offset"), TEXT("Spawn/duplicate offset as [x, y, z]."), TEXT("number"));
			Schema.String(TEXT("parentActor"), TEXT("Parent actor name to attach to."));
			Schema.FreeformObject(TEXT("properties"), TEXT("Component property key-value pairs."));
			Schema.String(TEXT("propertyName"), TEXT("Component property name to read or write."));
			Schema.Array(TEXT("rotation"), TEXT("Rotation as [pitch, yaw, roll] in degrees."), TEXT("number"));
			Schema.Array(TEXT("scale"), TEXT("Scale as [x, y, z]."), TEXT("number"));
			Schema.String(TEXT("snapshotName"), TEXT("Name for the actor snapshot."));
			Schema.StringEnum(TEXT("spawnKind"), { TEXT("class"), TEXT("blueprint") }, TEXT("Which spawn variant to run; omit for 'class'."));
			Schema.String(TEXT("tag"), TEXT("Gameplay tag string to add, remove, or find."));
			Schema.StringEnum(TEXT("tagOp"), { TEXT("add"), TEXT("remove") }, TEXT("Which add tag variant to run; omit for 'add'."));
			Schema.StringEnum(TEXT("transformMode"), { TEXT("transform"), TEXT("location"), TEXT("rotation"), TEXT("scale"), TEXT("teleport") }, TEXT("Which set transform variant to run; omit for 'transform'."));
			Schema.AnyValue(TEXT("value"), TEXT("Property value (any type)."));
			Schema.FreeformObject(TEXT("variables"), TEXT("Blueprint variable name to value map."));
			Schema.Bool(TEXT("visible"), TEXT("Desired visibility state."));
			Schema.StringEnum(TEXT("action"), { TEXT("spawn"), TEXT("duplicate"), TEXT("delete"), TEXT("set_transform"), TEXT("get_transform"), TEXT("apply_force"), TEXT("edit_component"), TEXT("get_component_property"), TEXT("set_material"), TEXT("set_visibility"), TEXT("get_components"), TEXT("list"), TEXT("add_tag"), TEXT("find_by_tag"), TEXT("find"), TEXT("attach"), TEXT("detach"), TEXT("set_blueprint_variables"), TEXT("create_snapshot"), TEXT("set_actor_collision"), TEXT("call_actor_function") }, TEXT("Action to invoke on control_actor."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};

class FMcpGenTool_ControlEditor : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("control_editor"); }
	FString GetDescription() const override { return TEXT("Start/stop PIE, control viewport camera, run console commands, take screenshots, simulate input."); }
	FString GetCategory() const override { return TEXT("core"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("actorName"), TEXT("Name of the actor to target."));
			Schema.Object(TEXT("arguments"), TEXT("Argument values keyed by parameter name. Converted per-property, so structs and arrays are accepted in their JSON form. Omitted parameters keep their zero-initialised default and are listed in unsetParameters."));
			Schema.String(TEXT("assetPath"), TEXT("Asset path (e.g. /Game/Path/Asset)."));
			Schema.Number(TEXT("blendTime"), TEXT("Blend time in seconds for set_view_target."));
			Schema.String(TEXT("bookmarkName"), TEXT("Bookmark name identifier."));
			Schema.String(TEXT("button"), TEXT("Mouse button for simulate_input."));
			Schema.StringEnum(TEXT("cameraOp"), { TEXT("transform"), TEXT("fov"), TEXT("view_target") }, TEXT("Which set camera variant to run; omit for 'transform'."));
			Schema.String(TEXT("category"), TEXT("Preferences category."));
			Schema.String(TEXT("className"), TEXT("Reflected class name, for example \"FabBrowserApi\"."));
			Schema.String(TEXT("classPath"), TEXT("Alias for className, the spelling the rest of the catalog uses."));
			Schema.String(TEXT("command"), TEXT("Console command string."));
			Schema.StringEnum(TEXT("control"), { TEXT("play"), TEXT("pause"), TEXT("resume"), TEXT("stop"), TEXT("eject"), TEXT("possess"), TEXT("speed"), TEXT("fixed_delta_time"), TEXT("step_frame"), TEXT("start") }, TEXT("Which play variant to run; omit for 'play'."));
			Schema.Number(TEXT("deltaTime"), TEXT("Fixed delta time in seconds."));
			Schema.String(TEXT("description"), TEXT("Bookmark description."));
			Schema.Number(TEXT("durationSeconds"), TEXT("Recording duration in seconds."));
			Schema.Bool(TEXT("enabled"), TEXT("Whether the feature is enabled."));
			Schema.String(TEXT("filename"), TEXT("Screenshot or recording filename."));
			Schema.String(TEXT("filter"), TEXT("Case-sensitive substring matched against function names."));
			Schema.Number(TEXT("fov"), TEXT("Camera field of view in degrees."));
			Schema.Number(TEXT("frameRate"), TEXT("Recording frame rate."));
			Schema.String(TEXT("functionName"), TEXT("Function name exactly as reported by describe_reflected_api."));
			Schema.Number(TEXT("height"), TEXT("Viewport height in pixels."));
			Schema.StringEnum(TEXT("history"), { TEXT("undo"), TEXT("redo") }, TEXT("Which undo variant to run; omit for 'undo'."));
			Schema.String(TEXT("id"), TEXT("Bookmark identifier."));
			Schema.Bool(TEXT("includeMetadata"), TEXT("Attach caller-provided metadata to the response."));
			Schema.String(TEXT("inputAction"), TEXT("Input action descriptor for simulate_input."));
			Schema.String(TEXT("inputType"), TEXT("Alias for type used by simulate_input."));
			Schema.String(TEXT("key"), TEXT("Input key name for simulate_input."));
			Schema.String(TEXT("levelPath"), TEXT("Level asset path."));
			Schema.Object(TEXT("location"), TEXT("3D location (x, y, z)."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("x"));
				  S.Number(TEXT("y"), TEXT("y"));
				  S.Number(TEXT("z"), TEXT("z"));
			});
			Schema.FreeformObject(TEXT("metadata"), TEXT("Caller-provided metadata."));
			Schema.String(TEXT("mode"), TEXT("Editor mode for set_editor_mode, or screenshot source."));
			Schema.String(TEXT("name"), TEXT("Name identifier."));
			Schema.String(TEXT("objectPath"), TEXT("Object path alias for actorName."));
			Schema.String(TEXT("path"), TEXT("Directory or file path."));
			Schema.FreeformObject(TEXT("preferences"), TEXT("Editor preferences key-value pairs."));
			Schema.Bool(TEXT("realtime"), TEXT("Whether realtime rendering is enabled."));
			Schema.String(TEXT("resolution"), TEXT("Maximum WxH for the returned PNG (e.g. \"1280x720\"). The capture is downscaled to fit inside this box with its aspect ratio preserved; a box at least as large as the viewport leaves the image untouched. Use this to bring an oversized capture under the base64 limit."));
			Schema.Bool(TEXT("returnBase64"), TEXT("Return PNG image data as base64. Defaults to false — a plain capture returns path + metadata. Set true for inline image data; pair with resolution= (e.g. \"1280x720\") to keep the PNG under the base64 size cap."));
			Schema.Object(TEXT("rotation"), TEXT("3D rotation (pitch, yaw, roll)."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("pitch"), TEXT("pitch"));
				  S.Number(TEXT("yaw"), TEXT("yaw"));
				  S.Number(TEXT("roll"), TEXT("roll"));
			});
			Schema.StringEnum(TEXT("setting"), { TEXT("open_tab"), TEXT("preferences"), TEXT("view_mode"), TEXT("editor_mode"), TEXT("game_view"), TEXT("immersive_mode"), TEXT("realtime"), TEXT("show_stats"), TEXT("hide_stats") }, TEXT("Which configure editor variant to run."));
			Schema.Number(TEXT("speed"), TEXT("Game speed multiplier."));
			Schema.String(TEXT("stat"), TEXT("Stat name to show or hide."));
			Schema.Integer(TEXT("steps"), TEXT("Number of frames to step."));
			Schema.String(TEXT("tabId"), TEXT("Registered nomad tab id, for example \"BridgeTab\" (Quixel Bridge) or \"FabTab\" (Fab)."));
			Schema.String(TEXT("type"), TEXT("Input event type (key_down, key_up, mouse_click, mouse_move)."));
			Schema.String(TEXT("viewMode"), TEXT("Viewport view mode (e.g. Lit, Unlit, Wireframe)."));
			Schema.Number(TEXT("width"), TEXT("Viewport width in pixels."));
			Schema.Number(TEXT("x"), TEXT("Mouse X coordinate for simulate_input."));
			Schema.Number(TEXT("y"), TEXT("Mouse Y coordinate for simulate_input."));
			Schema.StringEnum(TEXT("action"), { TEXT("play"), TEXT("set_game_speed"), TEXT("start_recording"), TEXT("set_camera"), TEXT("configure_viewport"), TEXT("set_viewport_resolution"), TEXT("invoke_reflected_function"), TEXT("describe_reflected_api"), TEXT("configure_editor"), TEXT("console_command"), TEXT("screenshot"), TEXT("create_bookmark"), TEXT("jump_to_bookmark"), TEXT("open_asset"), TEXT("close_asset"), TEXT("open_level"), TEXT("focus_actor"), TEXT("save_all"), TEXT("simulate_input"), TEXT("undo") }, TEXT("Action to invoke on control_editor."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};

class FMcpGenTool_Inspect : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("inspect"); }
	FString GetDescription() const override { return TEXT("Inspect any UObject: read/write properties, list components, export snapshots, and query class info. Actions: inspect_cdo (Blueprint CDO properties + all components without spawning an actor; use blueprintPath, optional detailed/componentName/propertyNames), inspect_class (class metadata), inspect_object (world actor), get_property/set_property, get_components, get_component_details (WORLD actors: actorName+componentName; a blueprintPath is routed to inspect_cdo), list_objects, find_by_class, find_by_tag, runtime_report."); }
	FString GetCategory() const override { return TEXT("core"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("actorName"), TEXT("World actor name to inspect."));
			Schema.String(TEXT("blueprintPath"), TEXT("Blueprint asset /Game path (for CDO/component inspection without spawning)."));
			Schema.String(TEXT("className"), TEXT("Class name or /Script/ class path to inspect."));
			Schema.String(TEXT("classPath"), TEXT("Class asset path (alias of className)."));
			Schema.String(TEXT("componentName"), TEXT("Component name on the actor."));
			Schema.Array(TEXT("componentNames"), TEXT("Specific component names to include."), TEXT("string"));
			Schema.Bool(TEXT("detailed"), TEXT("Return detailed property/component information."));
			Schema.StringEnum(TEXT("editorState"), { TEXT("selected_actors"), TEXT("viewport"), TEXT("world_settings"), TEXT("project_settings"), TEXT("editor_settings") }, TEXT("Which get editor state variant to run."));
			Schema.String(TEXT("filter"), TEXT("Runtime report filter expression."));
			Schema.StringEnum(TEXT("info"), { TEXT("details"), TEXT("property") }, TEXT("Which get component details variant to run; omit for 'details'."));
			Schema.StringEnum(TEXT("kind"), { TEXT("class"), TEXT("struct"), TEXT("cdo") }, TEXT("Which inspect class variant to run; omit for 'class'."));
			Schema.StringEnum(TEXT("lookup"), { TEXT("list"), TEXT("by_tag"), TEXT("metadata"), TEXT("bounding_box"), TEXT("export") }, TEXT("Which query object variant to run."));
			Schema.String(TEXT("name"), TEXT("Actor name identifier (alias of actorName)."));
			Schema.StringEnum(TEXT("objectKind"), { TEXT("object"), TEXT("actor"), TEXT("level"), TEXT("material"), TEXT("mesh"), TEXT("texture") }, TEXT("Which inspect object variant to run; omit for 'object'."));
			Schema.String(TEXT("objectPath"), TEXT("Object path of the world actor or asset (e.g. /Game/Maps/Demo.Demo_PersistentLevel)."));
			Schema.String(TEXT("propertyName"), TEXT("Property name to read or write."));
			Schema.Array(TEXT("propertyNames"), TEXT("Specific property names to include."), TEXT("string"));
			Schema.String(TEXT("propertyPath"), TEXT("Property path (alias of propertyName)."));
			Schema.String(TEXT("snapshotName"), TEXT("Snapshot name for create/restore."));
			Schema.StringEnum(TEXT("snapshotOp"), { TEXT("create"), TEXT("restore") }, TEXT("Which create snapshot variant to run; omit for 'create'."));
			Schema.StringEnum(TEXT("statsKind"), { TEXT("performance"), TEXT("memory"), TEXT("scene") }, TEXT("Which get stats variant to run."));
			Schema.String(TEXT("structPath"), TEXT("UserDefinedStruct asset /Game path to introspect."));
			Schema.String(TEXT("tag"), TEXT("Actor tag to match."));
			Schema.AnyValue(TEXT("value"), TEXT("Property value to set (type depends on the target property)."));
			Schema.StringEnum(TEXT("action"), { TEXT("inspect_object"), TEXT("get_blueprint_details"), TEXT("get_property"), TEXT("set_property"), TEXT("inspect_class"), TEXT("get_components"), TEXT("get_component_details"), TEXT("set_component_property"), TEXT("query_object"), TEXT("add_tag"), TEXT("create_snapshot"), TEXT("delete_object"), TEXT("find_by_class"), TEXT("runtime_report"), TEXT("get_editor_state"), TEXT("get_stats") }, TEXT("Action to invoke on inspect."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};

class FMcpGenTool_ManageLevel : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_level"); }
	FString GetDescription() const override { return TEXT("Load/save levels, configure streaming, and build lighting."); }
	FString GetCategory() const override { return TEXT("core"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("assetPath"), TEXT("Alias of levelPath resolved by the manage_level argument normalizer."));
			Schema.Array(TEXT("color"), TEXT("Linear color [r, g, b] or [r, g, b, a]."), TEXT("number"));
			Schema.String(TEXT("destinationPath"), TEXT("Destination path for move/copy."));
			Schema.Bool(TEXT("enableWorldBoundsChecks"), TEXT("Whether actors leaving the world bounds are culled."));
			Schema.String(TEXT("exportPath"), TEXT("Export file path."));
			Schema.String(TEXT("gameMode"), TEXT("GameMode override for the level. Accepts the Blueprint asset path or its generated _C class path."));
			Schema.Number(TEXT("gravityZ"), TEXT("World gravity along Z; setting it also enables the global gravity override."));
			Schema.StringEnum(TEXT("info"), { TEXT("summary"), TEXT("current_level") }, TEXT("Which get summary variant to run; omit for 'summary'."));
			Schema.Number(TEXT("intensity"), TEXT("Light intensity."));
			Schema.Number(TEXT("killZ"), TEXT("Z height below which actors are destroyed."));
			Schema.String(TEXT("levelName"), TEXT("Level name identifier."));
			Schema.StringEnum(TEXT("levelOp"), { TEXT("duplicate"), TEXT("rename") }, TEXT("Which duplicate level variant to run; omit for 'duplicate'."));
			Schema.String(TEXT("levelPath"), TEXT("Level asset path (e.g. /Game/Maps/Demo)."));
			Schema.Array(TEXT("levelPaths"), TEXT("Array of level asset paths."), TEXT("string"));
			Schema.String(TEXT("lightType"), TEXT("Light type: Point, Directional, Spot, Sky, or Rect (short/class/lowercase accepted)."));
			Schema.FreeformObject(TEXT("location"), TEXT("Actor world location {x, y, z}."));
			Schema.FreeformObject(TEXT("metadata"), TEXT("Metadata key/value pairs to write."));
			Schema.String(TEXT("name"), TEXT("Light actor name."));
			Schema.String(TEXT("newName"), TEXT("New name for the level asset."));
			Schema.Bool(TEXT("overwrite"), TEXT("Overwrite if the destination already exists."));
			Schema.String(TEXT("packagePath"), TEXT("Package path for import."));
			Schema.String(TEXT("parentLevel"), TEXT("Parent level path for the sub-level."));
			Schema.String(TEXT("parentPath"), TEXT("Parent directory path for the sub-level."));
			Schema.String(TEXT("path"), TEXT("Alias of levelPath resolved by the manage_level argument normalizer."));
			Schema.String(TEXT("quality"), TEXT("Lighting build quality: Preview, Medium, High, or Production."));
			Schema.FreeformObject(TEXT("rotation"), TEXT("Actor rotation {pitch, yaw, roll} or {x, y, z, w}."));
			Schema.Bool(TEXT("saveDirtyPackages"), TEXT("Save dirty packages before the operation."));
			Schema.StringEnum(TEXT("saveMode"), { TEXT("save"), TEXT("as") }, TEXT("Which save variant to run; omit for 'save'."));
			Schema.String(TEXT("savePath"), TEXT("Path to save the level asset."));
			Schema.Bool(TEXT("shouldBeLoaded"), TEXT("Whether the level should be loaded."));
			Schema.Bool(TEXT("shouldBeVisible"), TEXT("Whether the level should be visible."));
			Schema.String(TEXT("sourcePath"), TEXT("Source path for import/move/copy."));
			Schema.StringEnum(TEXT("streamOp"), { TEXT("stream"), TEXT("unload") }, TEXT("Which stream variant to run; omit for 'stream'."));
			Schema.Bool(TEXT("streaming"), TEXT("Load the level in streaming mode."));
			Schema.String(TEXT("streamingMethod"), TEXT("Streaming method: Blueprint or AlwaysLoaded."));
			Schema.String(TEXT("subLevelPath"), TEXT("Sub-level asset path to add as a streaming child."));
			Schema.String(TEXT("sublevelPath"), TEXT("Alias of subLevelPath resolved by the manage_level argument normalizer."));
			Schema.String(TEXT("targetPath"), TEXT("Alias of destinationPath resolved by the manage_level argument normalizer."));
			Schema.String(TEXT("template"), TEXT("Level template path accepted for compatibility; create_level dispatch does not apply it."));
			Schema.Number(TEXT("timeDilation"), TEXT("Global time dilation multiplier for the level."));
			Schema.Bool(TEXT("useWorldPartition"), TEXT("Create the level with World Partition enabled."));
			Schema.StringEnum(TEXT("action"), { TEXT("load"), TEXT("save"), TEXT("create_level"), TEXT("delete"), TEXT("duplicate_level"), TEXT("stream"), TEXT("unload_level"), TEXT("create_light"), TEXT("build_lighting"), TEXT("set_metadata"), TEXT("set_world_settings"), TEXT("list_levels"), TEXT("get_summary"), TEXT("validate_level"), TEXT("export_level"), TEXT("import_level"), TEXT("add_sublevel") }, TEXT("Action to invoke on manage_level."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedCore_ActorCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ControlActor());

	Registry.Register(new FMcpGenTool_ControlEditor());

	Registry.Register(new FMcpGenTool_Inspect());

	Registry.Register(new FMcpGenTool_ManageLevel());

}
