// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ManageGeometry : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_geometry"); }
	FString GetDescription() const override { return TEXT("Create procedural meshes using Geometry Script: booleans, deformers, UVs, collision, and LOD generation."); }
	FString GetCategory() const override { return TEXT("world"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.Number(TEXT("a"), TEXT("Alpha channel, 0-1."));
			Schema.String(TEXT("actorName"), TEXT("Actor name in the level."));
			Schema.Number(TEXT("amount"), TEXT("Generic amount (bevel size, inset/extrude distance)."));
			Schema.Number(TEXT("angle"), TEXT("Angle in degrees."));
			Schema.StringEnum(TEXT("arrayMode"), { TEXT("linear"), TEXT("radial") }, TEXT("Which array mesh variant to run."));
			Schema.String(TEXT("assetPath"), TEXT("Canonical /Game asset path."));
			Schema.String(TEXT("axis"), TEXT("Deformation axis: X, Y, or Z."));
			Schema.Number(TEXT("b"), TEXT("Blue channel, 0-1."));
			Schema.StringEnum(TEXT("booleanOp"), { TEXT("union"), TEXT("subtract"), TEXT("intersection"), TEXT("trim"), TEXT("self_union") }, TEXT("Which boolean mesh variant to run."));
			Schema.Bool(TEXT("cap"), TEXT("Cap open ends of tubes."));
			Schema.Object(TEXT("center"), TEXT("Center of operation."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.StringEnum(TEXT("collisionOp"), { TEXT("generate"), TEXT("generate_complex"), TEXT("simplify") }, TEXT("Which configure mesh collision variant to run."));
			Schema.String(TEXT("collisionType"), TEXT("Collision complexity type."));
			Schema.Bool(TEXT("computeWeightedNormals"), TEXT("Use area-weighted normals."));
			Schema.Integer(TEXT("count"), TEXT("Count of repeated elements."));
			Schema.StringEnum(TEXT("deform"), { TEXT("bend"), TEXT("twist"), TEXT("taper"), TEXT("stretch"), TEXT("spherify"), TEXT("cylindrify"), TEXT("smooth"), TEXT("relax"), TEXT("noise_deform"), TEXT("lattice_deform"), TEXT("displace_by_texture"), TEXT("poke"), TEXT("triangulate") }, TEXT("Which deform mesh variant to run."));
			Schema.Number(TEXT("depth"), TEXT("Primitive depth along Z."));
			Schema.Integer(TEXT("depthSegments"), TEXT("Tessellation segments along depth."));
			Schema.Object(TEXT("dimensions"), TEXT("Primitive dimensions {x, y, z}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Number(TEXT("distance"), TEXT("Distance for offset-style operations."));
			Schema.StringEnum(TEXT("edit"), { TEXT("create"), TEXT("append_vertex"), TEXT("append_triangle"), TEXT("set_vertex_position"), TEXT("set_vertex_color"), TEXT("set_uvs"), TEXT("split_normals"), TEXT("translate"), TEXT("difference") }, TEXT("Which edit dynamic mesh variant to run."));
			Schema.Bool(TEXT("enableCollision"), TEXT("Enable simple collision on the created DynamicMesh actor."));
			Schema.Number(TEXT("g"), TEXT("Green channel, 0-1."));
			Schema.Integer(TEXT("groupID"), TEXT("Polygroup id assigned to the appended triangle."));
			Schema.Number(TEXT("hardEdgeAngle"), TEXT("Angle threshold for hard edges (degrees)."));
			Schema.Number(TEXT("height"), TEXT("Primitive height."));
			Schema.Number(TEXT("heightScale"), TEXT("Texture displacement height scale."));
			Schema.Integer(TEXT("heightSegments"), TEXT("Tessellation segments along height."));
			Schema.Integer(TEXT("hullCount"), TEXT("Number of convex hulls for decomposition."));
			Schema.Number(TEXT("hullPrecision"), TEXT("Precision for convex hull generation."));
			Schema.Number(TEXT("innerRadius"), TEXT("Inner radius (torus minor radius, ring/pipe inner wall)."));
			Schema.Integer(TEXT("iterations"), TEXT("Number of iterations for smooth/remesh."));
			Schema.Bool(TEXT("keepInside"), TEXT("Keep geometry inside the tool."));
			Schema.Bool(TEXT("keepTool"), TEXT("Keep the tool actor after the operation."));
			Schema.Integer(TEXT("latticeResolution"), TEXT("Control lattice resolution for lattice deformation."));
			Schema.Object(TEXT("location"), TEXT("World location {x, y, z}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Integer(TEXT("lodCount"), TEXT("Number of LOD levels to generate."));
			Schema.Integer(TEXT("lodIndex"), TEXT("Specific LOD index to configure."));
			Schema.StringEnum(TEXT("lodOp"), { TEXT("generate"), TEXT("set_settings"), TEXT("set_screen_sizes") }, TEXT("Which configure mesh lods variant to run."));
			Schema.Integer(TEXT("maxHullCount"), TEXT("Maximum hull count for complex collision generation."));
			Schema.Integer(TEXT("maxHullVerts"), TEXT("Maximum vertices per hull for complex collision generation."));
			Schema.Integer(TEXT("maxVerticesPerHull"), TEXT("Maximum vertices per convex hull."));
			Schema.Number(TEXT("midpoint"), TEXT("Texture luminance midpoint for displacement."));
			Schema.StringEnum(TEXT("modeling"), { TEXT("extrude"), TEXT("inset"), TEXT("outset"), TEXT("offset_faces"), TEXT("bevel"), TEXT("chamfer"), TEXT("bridge"), TEXT("loft"), TEXT("sweep"), TEXT("revolve"), TEXT("shell"), TEXT("loop_cut"), TEXT("edge_split"), TEXT("quadrangulate"), TEXT("extrude_along_spline"), TEXT("duplicate_along_spline") }, TEXT("Which model mesh variant to run."));
			Schema.String(TEXT("name"), TEXT("Name for the new asset or node."));
			Schema.Integer(TEXT("numRings"), TEXT("Number of rings for sphere, capsule, torus, arch."));
			Schema.Integer(TEXT("numSides"), TEXT("Number of sides for cylinder, cone, disc, ring, torus."));
			Schema.Integer(TEXT("numSteps"), TEXT("Number of steps for stair primitives."));
			Schema.Number(TEXT("numTurns"), TEXT("Number of turns for spiral stairs (converted to a curve angle)."));
			Schema.Object(TEXT("offset"), TEXT("Offset vector."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.StringEnum(TEXT("optimization"), { TEXT("simplify_mesh"), TEXT("remesh_uniform"), TEXT("remesh_voxel"), TEXT("subdivide"), TEXT("merge_vertices"), TEXT("weld_vertices"), TEXT("remove_degenerates"), TEXT("fill_holes"), TEXT("flip_normals"), TEXT("recalculate_normals"), TEXT("recompute_tangents") }, TEXT("Which optimize mesh variant to run."));
			Schema.Number(TEXT("outerRadius"), TEXT("Outer radius for ring and pipe primitives."));
			Schema.String(TEXT("outputPath"), TEXT("Canonical /Game output asset path."));
			Schema.Object(TEXT("position"), TEXT("Position {x, y, z} for the operation."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.StringEnum(TEXT("primitive"), { TEXT("box"), TEXT("sphere"), TEXT("cylinder"), TEXT("cone"), TEXT("capsule"), TEXT("plane"), TEXT("disc"), TEXT("ring"), TEXT("torus"), TEXT("pipe"), TEXT("arch"), TEXT("ramp"), TEXT("stairs"), TEXT("spiral_stairs") }, TEXT("Which create primitive variant to run."));
			Schema.Number(TEXT("r"), TEXT("Red channel, 0-1."));
			Schema.Integer(TEXT("radialSegments"), TEXT("Radial tessellation segments for circular primitives."));
			Schema.Number(TEXT("radius"), TEXT("Primitive radius."));
			Schema.Bool(TEXT("recomputeNormals"), TEXT("Recompute normals for the LOD."));
			Schema.Bool(TEXT("recomputeTangents"), TEXT("Recompute tangents for the LOD."));
			Schema.Number(TEXT("reductionPercent"), TEXT("Percent of triangles to reduce."));
			Schema.AnyValue(TEXT("rotation"), TEXT("Rotation {pitch, yaw, roll}."));
			Schema.Object(TEXT("scale"), TEXT("Spawn scale {x, y, z}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Array(TEXT("screenSizes"), TEXT("Screen size for each LOD."), TEXT("number"));
			Schema.Integer(TEXT("segments"), TEXT("Number of segments for the operation."));
			Schema.Bool(TEXT("setAll"), TEXT("Apply the colour to every vertex instead of one."));
			Schema.Number(TEXT("simplificationFactor"), TEXT("Collision simplification factor."));
			Schema.String(TEXT("splineActorName"), TEXT("Spline actor name for extrude/sweep along spline."));
			Schema.Number(TEXT("splitAngle"), TEXT("Angle threshold in degrees above which normals are split."));
			Schema.Number(TEXT("stepDepth"), TEXT("Depth of each stair step."));
			Schema.Number(TEXT("stepHeight"), TEXT("Height of each stair step."));
			Schema.Number(TEXT("stepWidth"), TEXT("Width of each stair step."));
			Schema.Integer(TEXT("steps"), TEXT("Number of steps."));
			Schema.Number(TEXT("strength"), TEXT("Deformation strength."));
			Schema.String(TEXT("targetActor"), TEXT("Target actor name for boolean operations."));
			Schema.Number(TEXT("targetEdgeLength"), TEXT("Target edge length for remeshing."));
			Schema.Integer(TEXT("targetHullCount"), TEXT("Target hull count for collision simplification."));
			Schema.Number(TEXT("targetTriangleCount"), TEXT("Target triangle count for simplification."));
			Schema.String(TEXT("texturePath"), TEXT("Canonical /Game texture asset path."));
			Schema.Number(TEXT("thickness"), TEXT("Shell wall thickness (scalar)."));
			Schema.String(TEXT("toolActor"), TEXT("Tool actor name for boolean operations."));
			Schema.Object(TEXT("translation"), TEXT("Translation {x, y, z} applied to every mesh vertex."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Array(TEXT("triangleIndices"), TEXT("Triangle ids the operation is limited to; omit to apply it to the whole mesh."), TEXT("integer"));
			Schema.Number(TEXT("trianglePercent"), TEXT("Percent of triangles to keep for LOD reduction."));
			Schema.String(TEXT("trimActorName"), TEXT("Trim actor name for boolean trim."));
			Schema.Number(TEXT("u"), TEXT("U coordinate."));
			Schema.Integer(TEXT("uvChannel"), TEXT("UV channel index (0-7)."));
			Schema.Object(TEXT("uvOffset"), TEXT("UV offset {u, v}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("u"), TEXT("U"));
				  S.Number(TEXT("v"), TEXT("V"));
			});
			Schema.StringEnum(TEXT("uvOp"), { TEXT("auto"), TEXT("unwrap"), TEXT("project"), TEXT("pack_islands"), TEXT("transform") }, TEXT("Which edit uvs variant to run."));
			Schema.Object(TEXT("uvScale"), TEXT("UV scale {u, v}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("u"), TEXT("U"));
				  S.Number(TEXT("v"), TEXT("V"));
			});
			Schema.Number(TEXT("v"), TEXT("V coordinate."));
			Schema.Object(TEXT("v0"), TEXT("First corner {x, y, z} of the appended triangle."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("v1"), TEXT("Second corner {x, y, z} of the appended triangle."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("v2"), TEXT("Third corner {x, y, z} of the appended triangle."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Integer(TEXT("vertexIndex"), TEXT("Index of the vertex the operation targets."));
			Schema.Number(TEXT("weight"), TEXT("Weight for lattice deformation."));
			Schema.Number(TEXT("weldDistance"), TEXT("Distance threshold for vertex welding."));
			Schema.Number(TEXT("width"), TEXT("Primitive width along X."));
			Schema.Integer(TEXT("widthSegments"), TEXT("Tessellation segments along width."));
			Schema.StringEnum(TEXT("action"), { TEXT("create_primitive"), TEXT("boolean_mesh"), TEXT("model_mesh"), TEXT("deform_mesh"), TEXT("mirror"), TEXT("array_mesh"), TEXT("optimize_mesh"), TEXT("edit_uvs"), TEXT("configure_mesh_collision"), TEXT("configure_mesh_lods"), TEXT("convert_to_nanite"), TEXT("convert_to_static_mesh"), TEXT("get_mesh_info"), TEXT("edit_dynamic_mesh"), TEXT("get_vertex_position") }, TEXT("Action to invoke on manage_geometry."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedWorld_GeometryCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ManageGeometry());

}
