// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ManageBlueprint : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_blueprint"); }
	FString GetDescription() const override { return TEXT("Create Blueprints and UMG widgets, add SCS/UI components, set defaults, and manipulate Blueprint graphs, bindings, and widget layouts."); }
	FString GetCategory() const override { return TEXT("core"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("actionPath"), TEXT("Enhanced Input action asset path accepted in place of inputActionPath."));
			Schema.Number(TEXT("activeIndex"), TEXT("Index shown first by a widget switcher."));
			Schema.FreeformObject(TEXT("alignment"), TEXT("Widget alignment (0-1)."));
			Schema.Bool(TEXT("alwaysShowScrollbar"), TEXT("Always show scrollbar."));
			Schema.FreeformObject(TEXT("anchorMax"), TEXT("Maximum anchor point (0-1)."));
			Schema.FreeformObject(TEXT("anchorMin"), TEXT("Minimum anchor point (0-1)."));
			Schema.Number(TEXT("angle"), TEXT("Render rotation angle in degrees."));
			Schema.String(TEXT("animationName"), TEXT("Widget animation name."));
			Schema.Bool(TEXT("applyAndSave"), TEXT("Whether to save the Blueprint after applying SCS changes."));
			Schema.String(TEXT("attachTo"), TEXT("Socket or parent component to attach to."));
			Schema.Bool(TEXT("autoWrap"), TEXT("Enable text auto-wrap."));
			Schema.StringEnum(TEXT("bindingKind"), { TEXT("text"), TEXT("color"), TEXT("enabled"), TEXT("visibility"), TEXT("on_clicked"), TEXT("on_hovered"), TEXT("on_value_changed"), TEXT("localized_text"), TEXT("property"), TEXT("localization_key"), TEXT("widget") }, TEXT("Which bind widget variant to run."));
			Schema.String(TEXT("bindingSource"), TEXT("Variable or function name to bind to."));
			Schema.String(TEXT("blueprintPath"), TEXT("Canonical /Game Blueprint asset path."));
			Schema.String(TEXT("blueprintType"), TEXT("Blueprint type hint for creation."));
			Schema.Number(TEXT("bottom"), TEXT("Bottom margin in slate units."));
			Schema.FreeformObject(TEXT("brushColor"), TEXT("Border brush color."));
			Schema.FreeformObject(TEXT("brushSize"), TEXT("Brush/image size."));
			Schema.String(TEXT("category"), TEXT("Category folder for the variable."));
			Schema.StringEnum(TEXT("clipping"), { TEXT("Inherit"), TEXT("ClipToBounds"), TEXT("ClipToBoundsWithoutIntersecting"), TEXT("ClipToBoundsAlways"), TEXT("OnDemand") }, TEXT("Widget clipping mode."));
			Schema.FreeformObject(TEXT("colorAndOpacity"), TEXT("Color and opacity (0-1 values)."));
			Schema.Number(TEXT("columnCount"), TEXT("Number of columns in a uniform/grid panel."));
			Schema.Number(TEXT("columns"), TEXT("Item columns in the generated shop grid."));
			Schema.String(TEXT("componentClass"), TEXT("Component class path for SCS node creation."));
			Schema.String(TEXT("componentName"), TEXT("Name for the SCS component node."));
			Schema.String(TEXT("componentType"), TEXT("Component class name to add."));
			Schema.StringEnum(TEXT("createMode"), { TEXT("create"), TEXT("blueprint"), TEXT("ensure") }, TEXT("Which create variant to run; omit for 'create'."));
			Schema.String(TEXT("customEventName"), TEXT("Custom event name to create."));
			Schema.AnyValue(TEXT("defaultValue"), TEXT("Default value for the variable or property."));
			Schema.StringEnum(TEXT("deleteScope"), { TEXT("node"), TEXT("pin_links") }, TEXT("Which delete node variant to run; omit for 'node'."));
			Schema.Number(TEXT("delta"), TEXT("Spinbox increment."));
			Schema.Number(TEXT("duration"), TEXT("Duration in seconds."));
			Schema.StringEnum(TEXT("edit"), { TEXT("add_node"), TEXT("create_node"), TEXT("create_reroute_node"), TEXT("create_struct_make_break_nodes"), TEXT("connect_pins"), TEXT("set_node_property"), TEXT("set_pin_default_value"), TEXT("add_construction_script"), TEXT("add_scs_component"), TEXT("add_component"), TEXT("modify"), TEXT("reparent"), TEXT("set_property"), TEXT("set_transform"), TEXT("add_variable"), TEXT("rename_variable"), TEXT("set_variable_metadata"), TEXT("set_metadata"), TEXT("set_default"), TEXT("create"), TEXT("add_track"), TEXT("add_keyframe"), TEXT("set_loop"), TEXT("set_parent_class"), TEXT("preview"), TEXT("rename_widget"), TEXT("reparent_widget") }, TEXT("Which edit graph variant to run."));
			Schema.String(TEXT("eventName"), TEXT("Custom event name."));
			Schema.String(TEXT("eventType"), TEXT("Event type string for add_event."));
			Schema.Bool(TEXT("explicitWrapWidth"), TEXT("Use explicit wrap width."));
			Schema.Number(TEXT("fadeTime"), TEXT("Fade time in seconds."));
			Schema.FreeformObject(TEXT("fillColorAndOpacity"), TEXT("Fill color for progress bar."));
			Schema.String(TEXT("folder"), TEXT("Destination /Game folder for a Widget Blueprint."));
			Schema.String(TEXT("font"), TEXT("Font asset path; the size is applied even when this is omitted."));
			Schema.Number(TEXT("fontSize"), TEXT("Font size."));
			Schema.String(TEXT("fromNodeId"), TEXT("Source node identifier for a pin connection."));
			Schema.String(TEXT("fromPinName"), TEXT("Source pin name for a pin connection."));
			Schema.String(TEXT("functionName"), TEXT("Alias of bindingSource: the function or variable that feeds the binding."));
			Schema.String(TEXT("graphName"), TEXT("Target graph name (Event Graph, Construction Script, etc.)."));
			Schema.FreeformObject(TEXT("gridSize"), TEXT("Inventory grid size {columns,rows}."));
			Schema.Number(TEXT("height"), TEXT("Height override."));
			Schema.Number(TEXT("heightOverride"), TEXT("Height override for size box."));
			Schema.String(TEXT("hintText"), TEXT("Placeholder hint text."));
			Schema.Bool(TEXT("includePins"), TEXT("When true, graph details include per-node pins and links."));
			Schema.Bool(TEXT("includeProgressBar"), TEXT("Include progress bar."));
			Schema.StringEnum(TEXT("info"), { TEXT("blueprint"), TEXT("property"), TEXT("graph"), TEXT("node"), TEXT("pins"), TEXT("node_types"), TEXT("widget"), TEXT("slot") }, TEXT("Which get blueprint variant to run; omit for 'blueprint'."));
			Schema.FreeformObject(TEXT("innerSlotPadding"), TEXT("Inner wrap box slot padding."));
			Schema.String(TEXT("inputActionAssetPath"), TEXT("Enhanced Input action asset path accepted in place of inputActionPath."));
			Schema.String(TEXT("inputActionPath"), TEXT("Enhanced Input action asset path for an EnhancedInputAction node."));
			Schema.String(TEXT("inputAxisName"), TEXT("Axis name for an InputAxis event node."));
			Schema.StringEnum(TEXT("inputType"), { TEXT("single"), TEXT("multi") }, TEXT("Text input type."));
			Schema.ArrayOfObjects(TEXT("inputs"), TEXT("Function input parameter descriptors."));
			Schema.StringEnum(TEXT("interpolation"), { TEXT("linear"), TEXT("cubic"), TEXT("constant") }, TEXT("Keyframe interpolation."));
			Schema.Bool(TEXT("isChecked"), TEXT("Checkbox checked state."));
			Schema.Bool(TEXT("isEnabled"), TEXT("Widget enabled state."));
			Schema.Bool(TEXT("isMarquee"), TEXT("Progress bar marquee mode."));
			Schema.Bool(TEXT("isPublic"), TEXT("Whether the variable is exposed to the editor/BP graph."));
			Schema.Bool(TEXT("isReplicated"), TEXT("Whether the variable is replicated."));
			Schema.String(TEXT("key"), TEXT("Localization key assigned to the text widget."));
			Schema.StringEnum(TEXT("kind"), { TEXT("function"), TEXT("event") }, TEXT("Which add function variant to run; omit for 'function'."));
			Schema.StringEnum(TEXT("layoutProperty"), { TEXT("anchor"), TEXT("position"), TEXT("size"), TEXT("alignment"), TEXT("padding"), TEXT("z_order"), TEXT("visibility"), TEXT("clipping"), TEXT("render_transform"), TEXT("style") }, TEXT("Which set widget layout variant to run."));
			Schema.Number(TEXT("left"), TEXT("Left margin in slate units."));
			Schema.String(TEXT("linkedTo"), TEXT("Target pin descriptor for a pin link."));
			Schema.FreeformObject(TEXT("location"), TEXT("Relative location {x, y, z} for an SCS component template."));
			Schema.Number(TEXT("loopCount"), TEXT("Number of loops (-1 for infinite)."));
			Schema.String(TEXT("materialPath"), TEXT("Material asset path for a component."));
			Schema.Number(TEXT("maxValue"), TEXT("Maximum slider/spinbox value."));
			Schema.Number(TEXT("maxVisibleObjectives"), TEXT("Maximum visible objectives."));
			Schema.String(TEXT("memberClass"), TEXT("Member class (function, variable, event, etc.)."));
			Schema.String(TEXT("memberName"), TEXT("Member (function/variable/event) name the node represents."));
			Schema.String(TEXT("meshPath"), TEXT("Static/Skeletal mesh asset path for a mesh component."));
			Schema.FreeformObject(TEXT("metadata"), TEXT("Arbitrary metadata key-value pairs."));
			Schema.Number(TEXT("minDesiredHeight"), TEXT("Minimum desired height."));
			Schema.Number(TEXT("minDesiredSlotHeight"), TEXT("Minimum slot height."));
			Schema.Number(TEXT("minDesiredSlotWidth"), TEXT("Minimum slot width."));
			Schema.Number(TEXT("minDesiredWidth"), TEXT("Minimum desired width."));
			Schema.Number(TEXT("minValue"), TEXT("Minimum slider/spinbox value."));
			Schema.String(TEXT("name"), TEXT("Name for the new Blueprint or asset."));
			Schema.String(TEXT("namespace"), TEXT("Localization namespace owning the key."));
			Schema.String(TEXT("newName"), TEXT("New name for a renamed variable, function, or component."));
			Schema.String(TEXT("newParent"), TEXT("New parent SCS node name."));
			Schema.String(TEXT("nodeGuid"), TEXT("Node GUID accepted in place of nodeId."));
			Schema.String(TEXT("nodeId"), TEXT("Existing node identifier returned by create_node or get_graph_details."));
			Schema.String(TEXT("nodeName"), TEXT("Human-readable node name."));
			Schema.String(TEXT("nodeType"), TEXT("Blueprint node type string for creation."));
			Schema.String(TEXT("oldName"), TEXT("Current variable name before renaming."));
			Schema.String(TEXT("onHoveredFunction"), TEXT("Function to call on hover."));
			Schema.String(TEXT("onUnhoveredFunction"), TEXT("Function to call on unhover."));
			Schema.AnyValue(TEXT("operations"), TEXT("Batch operations for probe_handle."));
			Schema.Array(TEXT("options"), TEXT("Combo box options."), TEXT("string"));
			Schema.StringEnum(TEXT("orientation"), { TEXT("Horizontal"), TEXT("Vertical") }, TEXT("Widget orientation."));
			Schema.ArrayOfObjects(TEXT("outputs"), TEXT("Function output parameter descriptors."));
			Schema.FreeformObject(TEXT("padding"), TEXT("Widget slot padding {left,top,right,bottom}."));
			Schema.ArrayOfObjects(TEXT("parameters"), TEXT("Function/event parameter descriptors."));
			Schema.String(TEXT("parentClass"), TEXT("Parent class path for Blueprint creation (e.g. /Script/Engine.Actor)."));
			Schema.String(TEXT("parentComponent"), TEXT("Parent SCS node name for reparenting."));
			Schema.String(TEXT("parentName"), TEXT("Optional parent panel name to add the widget under."));
			Schema.String(TEXT("parentSlot"), TEXT("Parent slot to add the widget to."));
			Schema.String(TEXT("path"), TEXT("Destination /Game folder for a new Widget Blueprint."));
			Schema.Number(TEXT("percent"), TEXT("Progress bar percentage (0-1)."));
			Schema.String(TEXT("pinName"), TEXT("Pin name on a graph node."));
			Schema.StringEnum(TEXT("playMode"), { TEXT("forward"), TEXT("reverse"), TEXT("pingpong") }, TEXT("Animation play mode."));
			Schema.Number(TEXT("posX"), TEXT("X coordinate for node placement."));
			Schema.Number(TEXT("posY"), TEXT("Y coordinate for node placement."));
			Schema.FreeformObject(TEXT("position"), TEXT("Widget position offset."));
			Schema.Number(TEXT("positionX"), TEXT("Canvas slot X position, applied only when the parent is a canvas panel."));
			Schema.Number(TEXT("positionY"), TEXT("Canvas slot Y position, applied only when the parent is a canvas panel."));
			Schema.String(TEXT("preset"), TEXT("Named anchor preset (e.g. TopCenter) applied in place of anchorMin/anchorMax."));
			Schema.StringEnum(TEXT("previewSize"), { TEXT("1080p"), TEXT("720p"), TEXT("mobile"), TEXT("custom") }, TEXT("Preview resolution preset."));
			Schema.String(TEXT("promptFormat"), TEXT("Interaction prompt format."));
			Schema.FreeformObject(TEXT("properties"), TEXT("Property bag applied to the CDO, component template, or node."));
			Schema.String(TEXT("property"), TEXT("Widget property being bound; it selects the binding type."));
			Schema.String(TEXT("propertyName"), TEXT("Property name to set on the CDO or component."));
			Schema.AnyValue(TEXT("propertyValue"), TEXT("Value to assign to the property."));
			Schema.Number(TEXT("right"), TEXT("Right margin in slate units."));
			Schema.FreeformObject(TEXT("rotation"), TEXT("Relative rotation {pitch, yaw, roll} for an SCS component template."));
			Schema.Number(TEXT("rowCount"), TEXT("Number of rows in a uniform/grid panel."));
			Schema.Bool(TEXT("saveAfterCompile"), TEXT("Whether to save the asset after compiling."));
			Schema.String(TEXT("savePath"), TEXT("Destination /Game folder for a new Blueprint."));
			Schema.FreeformObject(TEXT("scale"), TEXT("Relative scale {x, y, z} for an SCS component template, or {x, y} for a widget render transform."));
			Schema.StringEnum(TEXT("screen"), { TEXT("credits"), TEXT("shop"), TEXT("main_menu"), TEXT("pause_menu"), TEXT("settings_menu"), TEXT("hud"), TEXT("dialog"), TEXT("inventory_ui"), TEXT("loading_screen"), TEXT("radial_menu") }, TEXT("Which create game screen variant to run."));
			Schema.StringEnum(TEXT("scrollBarVisibility"), { TEXT("Visible"), TEXT("Collapsed"), TEXT("Auto") }, TEXT("Scroll bar visibility."));
			Schema.Number(TEXT("segmentCount"), TEXT("Number of radial segments."));
			Schema.String(TEXT("selectedOption"), TEXT("Selected combo box option."));
			Schema.StringEnum(TEXT("settingsType"), { TEXT("video"), TEXT("audio"), TEXT("controls"), TEXT("gameplay"), TEXT("all") }, TEXT("Settings menu type."));
			Schema.FreeformObject(TEXT("shear"), TEXT("Render shear."));
			Schema.Bool(TEXT("showSpeakerName"), TEXT("Show speaker name in dialog."));
			Schema.FreeformObject(TEXT("size"), TEXT("Widget size override {x,y}."));
			Schema.Number(TEXT("sizeX"), TEXT("Slot width in slate units."));
			Schema.Number(TEXT("sizeY"), TEXT("Slot height in slate units."));
			Schema.String(TEXT("slotName"), TEXT("Slot name for a child widget inside its parent."));
			Schema.FreeformObject(TEXT("slotPadding"), TEXT("Padding between uniform grid slots."));
			Schema.String(TEXT("sourceNode"), TEXT("Source node id accepted in place of fromNodeId."));
			Schema.String(TEXT("sourcePin"), TEXT("Source pin name on the originating node."));
			Schema.Number(TEXT("stepSize"), TEXT("Value step size for slider."));
			Schema.StringEnum(TEXT("stretch"), { TEXT("None"), TEXT("Fill"), TEXT("ScaleToFit"), TEXT("ScaleToFitX"), TEXT("ScaleToFitY"), TEXT("ScaleToFill"), TEXT("UserSpecified") }, TEXT("Scale box stretch mode."));
			Schema.StringEnum(TEXT("stretchDirection"), { TEXT("Both"), TEXT("DownOnly"), TEXT("UpOnly") }, TEXT("Scale box stretch direction."));
			Schema.String(TEXT("stringKey"), TEXT("Key looked up within the string table."));
			Schema.String(TEXT("stringTableId"), TEXT("String table asset backing a localized text binding."));
			Schema.String(TEXT("structPath"), TEXT("Blueprint Struct asset path (UserDefinedStruct or native UScriptStruct)."));
			Schema.String(TEXT("targetClass"), TEXT("Target class for a class-member node."));
			Schema.String(TEXT("targetNode"), TEXT("Target node id accepted in place of toNodeId."));
			Schema.String(TEXT("targetPin"), TEXT("Target pin name on the destination node."));
			Schema.String(TEXT("targetWidget"), TEXT("Name of the widget inside the tree that receives the binding."));
			Schema.String(TEXT("text"), TEXT("Text content for a text block or button."));
			Schema.StringEnum(TEXT("textStyle"), { TEXT("font"), TEXT("margin") }, TEXT("Which set font variant to run; omit for 'font'."));
			Schema.String(TEXT("texturePath"), TEXT("Texture asset path for an image or brush."));
			Schema.Number(TEXT("time"), TEXT("Keyframe time."));
			Schema.String(TEXT("title"), TEXT("Title text for a menu template."));
			Schema.String(TEXT("toNodeId"), TEXT("Target node identifier for a pin connection."));
			Schema.String(TEXT("toPinName"), TEXT("Target pin name for a pin connection."));
			Schema.Number(TEXT("top"), TEXT("Top margin in slate units."));
			Schema.StringEnum(TEXT("trackType"), { TEXT("transform"), TEXT("color"), TEXT("opacity"), TEXT("renderOpacity"), TEXT("material"), TEXT("translation"), TEXT("scale"), TEXT("angle"), TEXT("shear") }, TEXT("Animation track type: opacity/renderOpacity (RenderOpacity), color (ColorAndOpacity), translation/scale/angle/shear or transform (RenderTransform)."));
			Schema.FreeformObject(TEXT("translation"), TEXT("Render translation offset."));
			Schema.Number(TEXT("userSpecifiedScale"), TEXT("User specified scale value."));
			Schema.Number(TEXT("value"), TEXT("Numeric value for a slider, spin box, or animation keyframe."));
			Schema.String(TEXT("variableName"), TEXT("Variable name to add, remove, rename, or modify."));
			Schema.String(TEXT("variableType"), TEXT("Variable type (Boolean, Float, Integer, Vector, String, Object)."));
			Schema.StringEnum(TEXT("visibility"), { TEXT("Visible"), TEXT("Collapsed"), TEXT("Hidden"), TEXT("HitTestInvisible"), TEXT("SelfHitTestInvisible") }, TEXT("Widget visibility state."));
			Schema.StringEnum(TEXT("widgetKind"), { TEXT("canvas_panel"), TEXT("overlay"), TEXT("vertical_box"), TEXT("horizontal_box"), TEXT("grid_panel"), TEXT("uniform_grid"), TEXT("wrap_box"), TEXT("border"), TEXT("scroll_box"), TEXT("size_box"), TEXT("scale_box"), TEXT("spacer"), TEXT("safe_zone"), TEXT("widget_switcher"), TEXT("health_bar"), TEXT("ammo_counter"), TEXT("crosshair"), TEXT("minimap"), TEXT("compass"), TEXT("damage_indicator"), TEXT("interaction_prompt"), TEXT("objective_tracker"), TEXT("quest_tracker"), TEXT("text_block"), TEXT("rich_text_block"), TEXT("image"), TEXT("button"), TEXT("check_box"), TEXT("combo_box"), TEXT("slider"), TEXT("spin_box"), TEXT("progress_bar"), TEXT("text_input"), TEXT("list_view"), TEXT("tree_view"), TEXT("component") }, TEXT("Which add content widget variant to run."));
			Schema.String(TEXT("widgetPath"), TEXT("Canonical /Game Widget Blueprint asset path."));
			Schema.Number(TEXT("width"), TEXT("Width override."));
			Schema.Number(TEXT("widthOverride"), TEXT("Width override for size box."));
			Schema.Number(TEXT("wrapWidth"), TEXT("Wrap width for wrap box."));
			Schema.Number(TEXT("x"), TEXT("Canvas X position for a HUD element (default 20)."));
			Schema.Number(TEXT("y"), TEXT("Canvas Y position for a HUD element (default 20)."));
			Schema.Number(TEXT("zOrder"), TEXT("Z-order for a canvas slot."));
			Schema.StringEnum(TEXT("action"), { TEXT("create"), TEXT("get_blueprint"), TEXT("compile"), TEXT("edit_scs"), TEXT("get_scs"), TEXT("remove_scs_component"), TEXT("edit_variable"), TEXT("remove_variable"), TEXT("edit_graph"), TEXT("delete_node"), TEXT("inspect_graph"), TEXT("add_function"), TEXT("remove_function"), TEXT("probe_handle"), TEXT("edit_widget_blueprint"), TEXT("remove_widget"), TEXT("add_panel_widget"), TEXT("add_content_widget"), TEXT("set_font"), TEXT("add_game_widget"), TEXT("create_game_screen"), TEXT("create_widget_template"), TEXT("set_widget_layout"), TEXT("bind_widget"), TEXT("edit_widget_animation"), TEXT("delete_animation"), TEXT("get_widget_info") }, TEXT("Action to invoke on manage_blueprint."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};

class FMcpGenTool_ManageTools : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_tools"); }
	FString GetDescription() const override { return TEXT("Dynamic MCP tool management. List canonical tools, view category counts, and enable/disable tools or categories at runtime."); }
	FString GetCategory() const override { return TEXT("core"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.StringEnum(TEXT("category"), { TEXT("core"), TEXT("world"), TEXT("gameplay"), TEXT("utility"), TEXT("all") }, TEXT("Category name to enable/disable."));
			Schema.Array(TEXT("tools"), TEXT("Tool names to enable or disable."), TEXT("string"));
			Schema.StringEnum(TEXT("action"), { TEXT("list_tools"), TEXT("list_categories"), TEXT("enable_tools"), TEXT("disable_tools"), TEXT("enable_category"), TEXT("disable_category"), TEXT("get_status"), TEXT("reset") }, TEXT("Action to invoke on manage_tools."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedCore_BlueprintCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ManageBlueprint());

	Registry.Register(new FMcpGenTool_ManageTools());

}
