// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.
#pragma once

#include "CoreMinimal.h"
#include "MCP/Registry/McpToolDefinition.h"
#include "MCP/Registry/McpToolRegistry.h"
#include "MCP/Registry/McpSchemaBuilder.h"

/**
 * Generated canonical parent tool registry (Task 23).
 *
 * One FMcpToolDefinition per canonical parent tool, built from the same
 * 23-tool contract source that drives the TypeScript gateway manifest.
 * Registered into FMcpToolRegistry at static-init time; the canonical-name
 * gate in McpToolRegistry.cpp admits exactly these 23 names.
 *
 * Union/any schema fields are emitted through first-class FMcpSchemaBuilder
 * methods (TypeUnion / AnyValue), so no shared helper block is required.
 */
class FMcpGeneratedParentRegistry
{
public:
	static void RegisterAll();

// One entry point per generated capability shard; RegisterAll() calls each.
	static void RegisterGeneratedCore_ActorCapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedCore_AssetCapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedCore_BlueprintCapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedCore_SystemCapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedGameplay_AICapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedGameplay_AnimCapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedGameplay_CombatCapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedGameplay_SysCapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedWorld_EnvironmentCapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedWorld_GeometryCapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedWorld_StructureCapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedUtility_AudioCapabilities(FMcpToolRegistry& Registry);
	static void RegisterGeneratedUtility_SequenceCapabilities(FMcpToolRegistry& Registry);
};

/**
 * Parameter-catalog fragments for parents whose schema is emitted into
 * separate translation units to stay within the source-size ceiling.
 * Each appends its parameters onto the builder it receives.
 */
namespace McpGeneratedParentSchema
{
	void AppendBuildEnvironmentFields(FMcpSchemaBuilder& Schema);
	void AppendBuildEnvironmentStructures(FMcpSchemaBuilder& Schema);
}
