// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ManageAsset : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_asset"); }
	FString GetDescription() const override { return TEXT("Create/import/manage assets, material graphs, material instances, procedural textures, render targets, and dependency analysis."); }
	FString GetCategory() const override { return TEXT("core"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.ArrayOfObjects(TEXT("additionalOutputs"), TEXT("Additional named output definitions."));
			Schema.StringEnum(TEXT("adjust"), { TEXT("curves"), TEXT("levels"), TEXT("blur"), TEXT("sharpen"), TEXT("desaturate"), TEXT("invert") }, TEXT("Which adjust texture variant to run."));
			Schema.String(TEXT("alphaTexture"), TEXT("Alpha channel source."));
			Schema.Number(TEXT("amount"), TEXT("Desaturation amount (0-1)."));
			Schema.String(TEXT("assetId"), TEXT("Fab asset id, used as the cache key."));
			Schema.String(TEXT("assetPath"), TEXT("Alias for path (accepted for compatibility)."));
			Schema.AnyValue(TEXT("assetPaths"), TEXT("Absolute paths of the downloaded pack files. Used with folderName to synthesize a single-entry envelope when payload is omitted."));
			Schema.String(TEXT("assetType"), TEXT("Bridge asset type: 3d, 3dplant, atlas or surface."));
			Schema.String(TEXT("baseTexture"), TEXT("Base texture path."));
			Schema.String(TEXT("blendMode"), TEXT("Blend mode."));
			Schema.String(TEXT("blendTexture"), TEXT("Blend texture path."));
			Schema.String(TEXT("blendType"), TEXT("Blend mode."));
			Schema.String(TEXT("blueTexture"), TEXT("Blue channel source."));
			Schema.String(TEXT("channel"), TEXT("Channel to adjust."));
			Schema.Bool(TEXT("checkoutFiles"), TEXT("Check out files in source control."));
			Schema.Array(TEXT("classNames"), TEXT("Asset class names to filter."), TEXT("string"));
			Schema.Bool(TEXT("clearExisting"), TEXT("Clear existing rows before import."));
			Schema.String(TEXT("code"), TEXT("HLSL code."));
			Schema.Array(TEXT("columnTypes"), TEXT("Column struct paths to read, for example \"/Script/Fab.FabObjectNameColumn\". Defaults to the columns Fab currently writes. Override this when a Fab update renames or adds columns; unresolved paths are reported rather than failing the call."), TEXT("string"));
			Schema.StringEnum(TEXT("compileOp"), { TEXT("compile"), TEXT("rebuild") }, TEXT("Which compile material variant to run; omit for 'compile'."));
			Schema.String(TEXT("compressionSettings"), TEXT("Compression format."));
			Schema.Number(TEXT("constA"), TEXT("Constant A."));
			Schema.Number(TEXT("constB"), TEXT("Constant B."));
			Schema.Number(TEXT("coordinateIndex"), TEXT("UV channel index (default 0)."));
			Schema.String(TEXT("cursor"), TEXT("Opaque pagination cursor returned by a previous list response. Forward verbatim to resume."));
			Schema.ArrayOfObjects(TEXT("curvePoints"), TEXT("Curve control points."));
			Schema.String(TEXT("dataTablePath"), TEXT("Asset path of the DataTable (e.g. /Game/DataTables/DT_MyTable)."));
			Schema.AnyValue(TEXT("defaultValue"), TEXT("Default RGBA value."));
			Schema.StringEnum(TEXT("deleteScope"), { TEXT("enum"), TEXT("value"), TEXT("row"), TEXT("all"), TEXT("struct"), TEXT("member") }, TEXT("Which delete data table row variant to run; omit for 'row'."));
			Schema.Number(TEXT("depth"), TEXT("Maximum recursion depth."));
			Schema.String(TEXT("description"), TEXT("Function description."));
			Schema.String(TEXT("destinationDirectory"), TEXT("Where the pack lands. Defaults to the Fab library cache directory, which list_fab_downloads and the fabLibrary source root both read."));
			Schema.String(TEXT("destinationName"), TEXT("New asset name."));
			Schema.TypeUnion(TEXT("destinationPath"), { TEXT("string") }, TEXT("Destination /Game asset path."));
			Schema.String(TEXT("direction"), TEXT("Connection direction to report (inputs or outputs)."));
			Schema.String(TEXT("directory"), TEXT("Directory to report on."));
			Schema.String(TEXT("directoryPath"), TEXT("Directory path to fix up."));
			Schema.String(TEXT("downloadType"), TEXT("Transfer mode: \"http\" or \"buildpatch\". BuildPatchServices is for Marketplace-era packs; pointing it at a plain URL stalls rather than failing, so it must be opted into."));
			Schema.String(TEXT("downloadUrl"), TEXT("Signed https download URL issued by Fab. Short-lived: a stale URL fails with DOWNLOAD_FAILED."));
			Schema.Bool(TEXT("downstream"), TEXT("Report downstream connections instead of upstream."));
			Schema.Bool(TEXT("dryRun"), TEXT("Report what would be copied without writing anything. Returns the same counts and packagePaths sample."));
			Schema.StringEnum(TEXT("edit"), { TEXT("add_parameter"), TEXT("reset_parameters"), TEXT("create_struct"), TEXT("add_struct_member"), TEXT("rename_struct_member"), TEXT("reorder_struct_members"), TEXT("set_struct_member_default"), TEXT("set_struct_member_metadata"), TEXT("set_struct_member_type"), TEXT("rename_struct"), TEXT("duplicate_struct"), TEXT("import_struct"), TEXT("recompile_struct"), TEXT("refresh_struct_dependencies"), TEXT("set_instanced_struct_property"), TEXT("create"), TEXT("add_value"), TEXT("rename_value"), TEXT("reorder_values"), TEXT("set_value_metadata"), TEXT("split"), TEXT("create_row_struct"), TEXT("add_row"), TEXT("update_row"), TEXT("import_rows"), TEXT("set_row_struct"), TEXT("set_struct_as_row_struct") }, TEXT("Which edit data table variant to run."));
			Schema.String(TEXT("endPin"), TEXT("Terminal pin name to stop the chain walk at."));
			Schema.String(TEXT("enumPath"), TEXT("Asset path of the UserDefinedEnum (e.g. /Game/Enums/E_MyEnum)."));
			Schema.String(TEXT("exportMode"), TEXT("Bridge export mode: normal, normal_drag or progressive."));
			Schema.Bool(TEXT("exposeToLibrary"), TEXT("Expose in the material function library."));
			Schema.Number(TEXT("expressionIndex"), TEXT("Expression index."));
			Schema.String(TEXT("filter"), TEXT("Case-sensitive substring matched against each serialized index entry."));
			Schema.String(TEXT("filterMethod"), TEXT("Resampling filter."));
			Schema.Bool(TEXT("fixupRedirectors"), TEXT("Fix up redirectors left behind by the deletion."));
			Schema.String(TEXT("folderName"), TEXT("Destination folder name under /Game/Megascans. Required when synthesizing from assetPaths."));
			Schema.String(TEXT("folderPath"), TEXT("Folder path for bulk operation."));
			Schema.Bool(TEXT("force"), TEXT("Force deletion even when the asset is still referenced (bridge delete path)."));
			Schema.String(TEXT("format"), TEXT("Pixel format."));
			Schema.Bool(TEXT("freeOnly"), TEXT("Restrict to free listings."));
			Schema.String(TEXT("functionPath"), TEXT("Material function /Game path."));
			Schema.Number(TEXT("gamma"), TEXT("Gamma."));
			Schema.String(TEXT("gradientType"), TEXT("Gradient type."));
			Schema.String(TEXT("greenTexture"), TEXT("Green channel source."));
			Schema.String(TEXT("group"), TEXT("Parameter group."));
			Schema.Number(TEXT("height"), TEXT("Height in pixels."));
			Schema.Number(TEXT("inBlack"), TEXT("Input black point."));
			Schema.Number(TEXT("inWhite"), TEXT("Input white point."));
			Schema.Bool(TEXT("includePackageCounts"), TEXT("Include packageCount per source. Costs a recursive file scan per returned entry, so leave off for a broad sweep and turn on once the candidate list is short."));
			Schema.Bool(TEXT("includeTags"), TEXT("When true, include asset tags in the listing response."));
			Schema.Number(TEXT("index"), TEXT("Split index."));
			Schema.StringEnum(TEXT("info"), { TEXT("material"), TEXT("function"), TEXT("find_node"), TEXT("node_details"), TEXT("node_properties"), TEXT("node_connections"), TEXT("node_chain"), TEXT("subgraph"), TEXT("row"), TEXT("rows"), TEXT("row_struct"), TEXT("struct"), TEXT("read"), TEXT("members"), TEXT("list"), TEXT("usage"), TEXT("compare"), TEXT("export"), TEXT("instanced_property") }, TEXT("Which get material info variant to run; omit for 'material'."));
			Schema.String(TEXT("inputName"), TEXT("Input name."));
			Schema.String(TEXT("inputType"), TEXT("Input type."));
			Schema.ArrayOfObjects(TEXT("inputs"), TEXT("Input definitions."));
			Schema.StringEnum(TEXT("io"), { TEXT("input"), TEXT("output") }, TEXT("Which add function io variant to run."));
			Schema.String(TEXT("key"), TEXT("Metadata key."));
			Schema.StringEnum(TEXT("kind"), { TEXT("assets"), TEXT("content_sources"), TEXT("material_instances"), TEXT("gradient"), TEXT("noise"), TEXT("pattern"), TEXT("ao_from_mesh"), TEXT("normal_from_height"), TEXT("resized"), TEXT("channel_pack"), TEXT("channel_extract"), TEXT("combined"), TEXT("material"), TEXT("decal"), TEXT("landscape"), TEXT("post_process"), TEXT("function"), TEXT("metadata"), TEXT("tags") }, TEXT("Which create material variant to run; omit for 'material'."));
			Schema.String(TEXT("layerName"), TEXT("Layer name."));
			Schema.ArrayOfObjects(TEXT("layers"), TEXT("Layer blend definitions."));
			Schema.Number(TEXT("levels"), TEXT("Noise level count."));
			Schema.TypeUnion(TEXT("limit"), { TEXT("number") }, TEXT("Maximum rows to return, clamped plugin-side."));
			Schema.String(TEXT("listingId"), TEXT("Fab listing uid, as it appears in a fab.com/listings/<uid> URL. Restricted to [A-Za-z0-9_-], 64 characters max, because it is used to build an API path."));
			Schema.Number(TEXT("lodBias"), TEXT("LOD bias value."));
			Schema.Number(TEXT("lodCount"), TEXT("Number of LOD levels to generate."));
			Schema.StringEnum(TEXT("lookup"), { TEXT("exists"), TEXT("search"), TEXT("by_tag"), TEXT("graph"), TEXT("material_stats"), TEXT("source_control_state"), TEXT("fab_listing_details"), TEXT("fab_downloads"), TEXT("fab_library"), TEXT("fab_search"), TEXT("megascans_library"), TEXT("metadata"), TEXT("dependencies"), TEXT("validate"), TEXT("report") }, TEXT("Which inspect asset variant to run."));
			Schema.StringEnum(TEXT("maintenance"), { TEXT("bulk_rename"), TEXT("fixup_redirectors"), TEXT("migrate") }, TEXT("Which maintain content variant to run."));
			Schema.StringEnum(TEXT("marketplace"), { TEXT("fab_listing"), TEXT("fab_download"), TEXT("megascans") }, TEXT("Which import marketplace asset variant to run."));
			Schema.String(TEXT("materialDomain"), TEXT("Material domain."));
			Schema.String(TEXT("materialPath"), TEXT("Material /Game asset path."));
			Schema.StringEnum(TEXT("materialProperty"), { TEXT("blend_mode"), TEXT("domain"), TEXT("shading_model"), TEXT("two_sided") }, TEXT("Which set material property variant to run."));
			Schema.Number(TEXT("maxDepth"), TEXT("Maximum traversal depth (clamped to 8)."));
			Schema.Number(TEXT("maxPackages"), TEXT("Refuse the migration when the source holds more files than this, so a mistyped source cannot copy tens of gigabytes. Narrow with subPath or raise deliberately."));
			Schema.String(TEXT("memberName"), TEXT("Member (variable) name."));
			Schema.String(TEXT("memberType"), TEXT("Unreal property type: Bool, Int, Float, String, Name, Text, Vector, Rotator, Transform, Object, SoftObject, Class, SoftClass, Enum:<Name>, Struct:<Path>, or with container prefix Array:..., Set:..., Map:<K>,<V>:"));
			Schema.ArrayOfObjects(TEXT("members"), TEXT("Member definitions."));
			Schema.String(TEXT("meshPath"), TEXT("Mesh /Game path."));
			Schema.AnyValue(TEXT("metadata"), TEXT("Metadata key-value pairs."));
			Schema.String(TEXT("name"), TEXT("DataTable name."));
			Schema.Bool(TEXT("neverStream"), TEXT("Never stream this texture."));
			Schema.String(TEXT("newEnumName"), TEXT("Name for the new enum."));
			Schema.Number(TEXT("newHeight"), TEXT("New height."));
			Schema.String(TEXT("newMemberName"), TEXT("New member name."));
			Schema.String(TEXT("newName"), TEXT("New asset name."));
			Schema.String(TEXT("newValueName"), TEXT("New enum value name."));
			Schema.Number(TEXT("newWidth"), TEXT("New width."));
			Schema.String(TEXT("nodeId"), TEXT("Node ID to delete."));
			Schema.Array(TEXT("nodeIds"), TEXT("Node IDs to delete in one batch, in place of nodeId."), TEXT("string"));
			Schema.StringEnum(TEXT("nodeKind"), { TEXT("node"), TEXT("custom_expression"), TEXT("fresnel"), TEXT("if"), TEXT("math"), TEXT("noise"), TEXT("panner"), TEXT("pixel_depth"), TEXT("reflection_vector"), TEXT("rotator"), TEXT("scalar_parameter"), TEXT("static_switch_parameter"), TEXT("switch"), TEXT("texture_coordinate"), TEXT("texture_sample"), TEXT("vector_parameter"), TEXT("vertex_normal"), TEXT("voronoi"), TEXT("world_position"), TEXT("material_function"), TEXT("landscape_layer") }, TEXT("Which add material node variant to run; omit for 'node'."));
			Schema.String(TEXT("nodeName"), TEXT("Node name to find."));
			Schema.String(TEXT("nodeType"), TEXT("Node type to find."));
			Schema.String(TEXT("noiseType"), TEXT("Noise type."));
			Schema.Number(TEXT("octaves"), TEXT("Noise octaves."));
			Schema.Number(TEXT("offset"), TEXT("Zero-based offset into the full result set."));
			Schema.Number(TEXT("opacity"), TEXT("Blend opacity."));
			Schema.String(TEXT("operation"), TEXT("Math operation (Add, Multiply, etc.)."));
			Schema.Array(TEXT("order"), TEXT("Desired value name order."), TEXT("string"));
			Schema.Bool(TEXT("orphansOnly"), TEXT("Report only orphaned nodes; accepted in place of nodeId."));
			Schema.String(TEXT("otherStructPath"), TEXT("Second struct path for comparison."));
			Schema.String(TEXT("outputPath"), TEXT("Output file path."));
			Schema.String(TEXT("outputType"), TEXT("Output type."));
			Schema.Bool(TEXT("overwrite"), TEXT("Overwrite existing asset at destination."));
			Schema.String(TEXT("packagePath"), TEXT("Package path (default /Game)."));
			Schema.Array(TEXT("packagePaths"), TEXT("Package paths to search within."), TEXT("string"));
			Schema.Object(TEXT("pagination"), TEXT("Nested pagination envelope. Top-level limit/offset take precedence when both are supplied."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("limit"), TEXT("Page size (1-500, default 50)."));
				  S.Number(TEXT("offset"), TEXT("Zero-based offset into the full result set."));
			});
			Schema.StringEnum(TEXT("parameterKind"), { TEXT("parameter"), TEXT("scalar"), TEXT("vector"), TEXT("texture"), TEXT("static_switch") }, TEXT("Which set material parameter variant to run; omit for 'parameter'."));
			Schema.String(TEXT("parameterName"), TEXT("Parameter name."));
			Schema.String(TEXT("parameterType"), TEXT("Parameter kind: scalar (default), vector, or texture. Selects which parameter expression the value is written to."));
			Schema.String(TEXT("parentMaterial"), TEXT("Parent material /Game path."));
			Schema.TypeUnion(TEXT("path"), { TEXT("string") }, TEXT("Alternative directory path."));
			Schema.AnyValue(TEXT("paths"), TEXT("Asset paths to check out."));
			Schema.String(TEXT("pattern"), TEXT("Search pattern (used when searchText is absent)."));
			Schema.String(TEXT("patternType"), TEXT("Pattern type."));
			Schema.Object(TEXT("payload"), TEXT("A complete Bridge export envelope: { exportPayload: [ { assetId, assetType, exportMode, exportType, folderName, name, assetPaths[] } ] }. Use this to pass through exactly what Bridge would have sent."));
			Schema.String(TEXT("pinName"), TEXT("Pin name."));
			Schema.Number(TEXT("posX"), TEXT("New X coordinate (fallback spelling)."));
			Schema.Number(TEXT("posY"), TEXT("New Y coordinate (fallback spelling)."));
			Schema.StringEnum(TEXT("position"), { TEXT("first"), TEXT("last"), TEXT("before"), TEXT("after") }, TEXT("Reorder anchor position."));
			Schema.String(TEXT("prefix"), TEXT("Name prefix."));
			Schema.StringEnum(TEXT("process"), { TEXT("thumbnail"), TEXT("lods") }, TEXT("Which process asset variant to run."));
			Schema.String(TEXT("propertyName"), TEXT("Property name."));
			Schema.String(TEXT("query"), TEXT("Free-text search. At most 128 characters, and no quotes, backslashes or control characters."));
			Schema.Number(TEXT("radius"), TEXT("Blur radius."));
			Schema.Bool(TEXT("recursive"), TEXT("Recurse into dependencies."));
			Schema.Bool(TEXT("recursiveClasses"), TEXT("Recurse into child classes."));
			Schema.Bool(TEXT("recursivePaths"), TEXT("Recurse into subdirectories."));
			Schema.String(TEXT("redTexture"), TEXT("Red channel source."));
			Schema.String(TEXT("relativeTo"), TEXT("Target member GUID/name."));
			Schema.String(TEXT("replaceText"), TEXT("Replacement text."));
			Schema.String(TEXT("replacement"), TEXT("Replacement text (used when replaceText is absent)."));
			Schema.String(TEXT("reportType"), TEXT("Report type."));
			Schema.Object(TEXT("rowData"), TEXT("Row data key/value map."));
			Schema.String(TEXT("rowName"), TEXT("Name of the row."));
			Schema.String(TEXT("rowStructPath"), TEXT("Asset path of the row UScriptStruct."));
			Schema.ArrayOfObjects(TEXT("rows"), TEXT("Rows to import, each { rowName: <name>, rowData: { <field>: <value>, ... } }. The field names inside rowData are the row struct own property names, e.g. { rowName: ArcRifle, rowData: { DisplayName: Arc Rifle, Damage: 42 } }. A flat entry such as { rowName, Damage } is rejected as missing rowData."));
			Schema.Number(TEXT("samples"), TEXT("AO samples."));
			Schema.Bool(TEXT("save"), TEXT("Persist the asset to disk. Defaults to false, which leaves it in memory only."));
			Schema.String(TEXT("savePath"), TEXT("Package path for the instance."));
			Schema.Number(TEXT("scale"), TEXT("Noise scale."));
			Schema.String(TEXT("searchScope"), TEXT("Optional path scope."));
			Schema.String(TEXT("searchText"), TEXT("Search pattern."));
			Schema.Number(TEXT("seed"), TEXT("Random seed."));
			Schema.StringEnum(TEXT("setting"), { TEXT("compression"), TEXT("lod_bias"), TEXT("streaming_priority"), TEXT("texture_group"), TEXT("virtual_texture") }, TEXT("Which configure texture variant to run."));
			Schema.String(TEXT("shadingModel"), TEXT("Shading model."));
			Schema.Bool(TEXT("showConfirmation"), TEXT("Show confirmation prompt."));
			Schema.StringEnum(TEXT("sourceControlOp"), { TEXT("checkout"), TEXT("submit") }, TEXT("Which source control variant to run."));
			Schema.String(TEXT("sourceId"), TEXT("Relative id under sourceRoot, exactly as returned by list_content_sources (for example \"TP_VehicleAdvBP\"). Must be relative: no \"..\", no leading \"/\", no drive prefix. Omit to migrate the root itself."));
			Schema.String(TEXT("sourceNodeId"), TEXT("Source node ID."));
			Schema.String(TEXT("sourcePath"), TEXT("Source /Game asset path."));
			Schema.String(TEXT("sourcePin"), TEXT("Source pin name."));
			Schema.String(TEXT("sourceRoot"), TEXT("Content source root token. One of: engineTemplates | engineFeaturePacks | engineContent | enginePlugins | megascansLibrary | fabLibrary | projectContent | projectPlugins. A filesystem path is never accepted here — the token is resolved plugin-side, so no directory outside these roots is reachable. megascansLibrary probes both the shell Documents folder and the profile Documents folder (OneDrive redirects the first) and honours MCP_MEGASCANS_LIBRARY_DIR; fabLibrary reads the Fab plugin's own UFabSettings.CacheDirectoryPath and honours MCP_FAB_LIBRARY_DIR. The Fab plugin owns its own sign-in and downloading — these roots only read what it already placed on disk."));
			Schema.String(TEXT("sourceTexture"), TEXT("Source heightmap texture path."));
			Schema.Number(TEXT("speed"), TEXT("Rotation speed."));
			Schema.Number(TEXT("speedX"), TEXT("Pan speed X."));
			Schema.Number(TEXT("speedY"), TEXT("Pan speed Y."));
			Schema.String(TEXT("startNodeId"), TEXT("Starting node ID accepted by the handler in place of nodeId."));
			Schema.Number(TEXT("streamingPriority"), TEXT("Texture streaming priority (default 0)."));
			Schema.Number(TEXT("strength"), TEXT("Normal strength."));
			Schema.String(TEXT("structPath"), TEXT("Asset path of the Blueprint Struct (e.g. /Game/Structs/S_MyStruct)."));
			Schema.String(TEXT("structType"), TEXT("Inner UScriptStruct asset path."));
			Schema.Object(TEXT("structValues"), TEXT("Field-name to value map."));
			Schema.String(TEXT("subPath"), TEXT("Optional folder under the source content directory, to migrate one subtree instead of the whole pack."));
			Schema.String(TEXT("suffix"), TEXT("Name suffix."));
			Schema.String(TEXT("tag"), TEXT("Tag name to search for."));
			Schema.Array(TEXT("tags"), TEXT("Tags to set."), TEXT("string"));
			Schema.String(TEXT("targetNodeId"), TEXT("Target node ID."));
			Schema.String(TEXT("targetPin"), TEXT("Target pin name."));
			Schema.String(TEXT("textureGroup"), TEXT("Texture group name."));
			Schema.String(TEXT("texturePath"), TEXT("Texture /Game asset path."));
			Schema.String(TEXT("tooltip"), TEXT("Member tooltip."));
			Schema.Bool(TEXT("twoSided"), TEXT("Two-sided flag."));
			Schema.String(TEXT("type"), TEXT("Node type (alias of nodeType)."));
			Schema.Number(TEXT("uTiling"), TEXT("U tiling factor (default 1)."));
			Schema.Bool(TEXT("upstream"), TEXT("Walk every upstream producer, overriding direction and depth."));
			Schema.Number(TEXT("vTiling"), TEXT("V tiling factor (default 1)."));
			Schema.AnyValue(TEXT("value"), TEXT("Default switch value."));
			Schema.String(TEXT("valueName"), TEXT("Enum value (entry) name."));
			Schema.Array(TEXT("values"), TEXT("Initial enum value names."), TEXT("string"));
			Schema.String(TEXT("varGuid"), TEXT("Stable member GUID."));
			Schema.Bool(TEXT("virtualTextureStreaming"), TEXT("Enable VT streaming."));
			Schema.Number(TEXT("width"), TEXT("Texture width in pixels (default 1024)."));
			Schema.Number(TEXT("x"), TEXT("New X coordinate (posX is the fallback spelling)."));
			Schema.Number(TEXT("y"), TEXT("New Y coordinate (posY is the fallback spelling)."));
			Schema.StringEnum(TEXT("action"), { TEXT("list"), TEXT("import"), TEXT("duplicate"), TEXT("rename"), TEXT("move"), TEXT("delete"), TEXT("create_folder"), TEXT("query_asset"), TEXT("query_marketplace"), TEXT("import_marketplace_asset"), TEXT("maintain_content"), TEXT("inspect_asset"), TEXT("process_asset"), TEXT("set_metadata"), TEXT("create_render_target"), TEXT("edit_material_instance"), TEXT("nanite_rebuild_mesh"), TEXT("bulk_delete"), TEXT("source_control"), TEXT("create_material"), TEXT("create_material_instance"), TEXT("add_material_node"), TEXT("connect_nodes"), TEXT("disconnect_nodes"), TEXT("get_material_info"), TEXT("set_material_parameter"), TEXT("delete_node"), TEXT("update_custom_expression"), TEXT("compile_material"), TEXT("set_node_position"), TEXT("set_material_property"), TEXT("add_function_io"), TEXT("configure_layer_blend"), TEXT("create_texture"), TEXT("adjust_texture"), TEXT("configure_texture"), TEXT("get_texture_info"), TEXT("edit_struct"), TEXT("get_struct"), TEXT("delete_struct"), TEXT("edit_data_table"), TEXT("inspect_data_table"), TEXT("delete_data_table_row"), TEXT("edit_enum"), TEXT("delete_enum"), TEXT("get_enum") }, TEXT("Action to invoke on manage_asset."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedCore_AssetCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ManageAsset());

}
