// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ManageLevelStructure : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_level_structure"); }
	FString GetDescription() const override { return TEXT("Structure worlds: levels, sublevels, World Partition, streaming, data layers, HLOD, level instances, trigger/blocking/physics/audio/post-process volumes, and nav bounds."); }
	FString GetCategory() const override { return TEXT("world"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("actorName"), TEXT("Actor name in the level."));
			Schema.String(TEXT("actorPath"), TEXT("Actor path in the level."));
			Schema.Bool(TEXT("bAutoCalculateBounds"), TEXT("Auto-calculate bounds from content."));
			Schema.Bool(TEXT("bBlockOnSlowStreaming"), TEXT("Block on slow streaming."));
			Schema.Bool(TEXT("bCreateWorldPartition"), TEXT("Create with World Partition enabled."));
			Schema.Bool(TEXT("bDisableDistanceStreaming"), TEXT("Disable distance-based streaming."));
			Schema.Bool(TEXT("bEnableWorldPartition"), TEXT("Enable World Partition for level."));
			Schema.Bool(TEXT("bEnabled"), TEXT("Whether the audio volume is enabled."));
			Schema.Bool(TEXT("bIsInitiallyLoaded"), TEXT("Data layer initially loaded."));
			Schema.Bool(TEXT("bIsInitiallyVisible"), TEXT("Data layer initially visible."));
			Schema.Bool(TEXT("bIsSpatiallyLoaded"), TEXT("HLOD is spatially loaded."));
			Schema.Bool(TEXT("bPackBlueprints"), TEXT("Include blueprints in packed level."));
			Schema.Bool(TEXT("bPackStaticMeshes"), TEXT("Include static meshes in packed level."));
			Schema.Bool(TEXT("bPainCausing"), TEXT("Whether the volume causes pain/damage."));
			Schema.Bool(TEXT("bShouldBeVisible"), TEXT("Level should be visible when loaded."));
			Schema.Bool(TEXT("bShouldBlockOnLoad"), TEXT("Block game until level is loaded."));
			Schema.Bool(TEXT("bUnbound"), TEXT("Whether post process volume affects entire world."));
			Schema.Bool(TEXT("bUseExternalActors"), TEXT("Enable One File Per Actor (OFPA) for Data Layer compatibility."));
			Schema.Bool(TEXT("bWaterVolume"), TEXT("Whether this is a water volume."));
			Schema.Number(TEXT("blendRadius"), TEXT("Blend radius for post process volume."));
			Schema.Number(TEXT("blendWeight"), TEXT("Blend weight (0.0-1.0) for post process."));
			Schema.Array(TEXT("bounds"), TEXT("Volume bounds as a six-number array [minX, minY, minZ, maxX, maxY, maxZ]."), TEXT("number"));
			Schema.Object(TEXT("boundsExtent"), TEXT("Extent of level bounds."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("boundsOrigin"), TEXT("Origin of level bounds."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("boxExtent"), TEXT("Extent for box trigger volumes."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Number(TEXT("capsuleHalfHeight"), TEXT("Half-height for capsule trigger volumes."));
			Schema.Number(TEXT("capsuleRadius"), TEXT("Radius for capsule trigger volumes."));
			Schema.Number(TEXT("cellSize"), TEXT("HLOD cell size."));
			Schema.Bool(TEXT("createIfMissing"), TEXT("Create the grid if missing."));
			Schema.Bool(TEXT("createVolume"), TEXT("Create a streaming volume (true) or report existing volumes (false)."));
			Schema.ArrayOfObjects(TEXT("cullDistances"), TEXT("Size/distance pairs for cull distance volumes."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("size"), TEXT("Object size threshold."));
				  S.Number(TEXT("cullDistance"), TEXT("Distance at which to cull."));
			});
			Schema.Number(TEXT("damagePerSec"), TEXT("Damage per second for pain volumes."));
			Schema.String(TEXT("dataLayerName"), TEXT("Data layer name."));
			Schema.String(TEXT("dataLayerType"), TEXT("Type of data layer: Runtime or Editor."));
			Schema.StringEnum(TEXT("edit"), { TEXT("open"), TEXT("add_node"), TEXT("connect_nodes"), TEXT("remove_node") }, TEXT("Which edit level blueprint variant to run."));
			Schema.Object(TEXT("extent"), TEXT("Extent (half-size) of the volume in each axis."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Number(TEXT("fadeTime"), TEXT("Fade time for audio volume."));
			Schema.String(TEXT("filter"), TEXT("Type filter for get_volumes_info (e.g. \"Trigger\", \"Physics\")."));
			Schema.Number(TEXT("fluidFriction"), TEXT("Fluid friction for physics volumes."));
			Schema.String(TEXT("functionName"), TEXT("Function to bind when nodeClass is K2Node_CallFunction (e.g. PrintString); short function names may also be passed as nodeClass."));
			Schema.Number(TEXT("gridCellSize"), TEXT("World Partition grid cell size."));
			Schema.String(TEXT("gridName"), TEXT("World Partition runtime hash set grid name."));
			Schema.String(TEXT("hlodLayerName"), TEXT("HLOD layer name."));
			Schema.String(TEXT("hlodLayerPath"), TEXT("Canonical /Game HLOD layer asset path."));
			Schema.Object(TEXT("instanceLocation"), TEXT("Location of the level instance."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("instanceRotation"), TEXT("Rotation of the level instance."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("pitch"), TEXT("Pitch"));
				  S.Number(TEXT("yaw"), TEXT("Yaw"));
				  S.Number(TEXT("roll"), TEXT("Roll"));
			});
			Schema.Object(TEXT("instanceScale"), TEXT("Scale of the level instance."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.StringEnum(TEXT("kind"), { TEXT("level"), TEXT("sublevel"), TEXT("level_instance"), TEXT("packed_level_actor"), TEXT("data_layer"), TEXT("minimap_volume") }, TEXT("Which create level structure variant to run."));
			Schema.String(TEXT("layerType"), TEXT("Layer type for runtime hash set grid."));
			Schema.String(TEXT("levelAssetPath"), TEXT("Canonical /Game level asset path for instancing."));
			Schema.String(TEXT("levelInstanceName"), TEXT("Level instance actor name."));
			Schema.String(TEXT("levelName"), TEXT("Level asset name."));
			Schema.String(TEXT("levelPath"), TEXT("Canonical /Game level asset path."));
			Schema.Number(TEXT("loadingDistance"), TEXT("HLOD loading distance."));
			Schema.Number(TEXT("loadingRange"), TEXT("Loading range for grid cells."));
			Schema.Object(TEXT("location"), TEXT("World location {x, y, z}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.String(TEXT("nodeClass"), TEXT("Level blueprint graph node class."));
			Schema.String(TEXT("nodeId"), TEXT("Node GUID returned by add_level_blueprint_node."));
			Schema.String(TEXT("nodeName"), TEXT("Level blueprint node name."));
			Schema.Object(TEXT("nodePosition"), TEXT("Node graph position {x, y}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
			});
			Schema.String(TEXT("packedLevelName"), TEXT("Name for the packed level actor."));
			Schema.String(TEXT("parentLevel"), TEXT("Parent level asset path."));
			Schema.Number(TEXT("priority"), TEXT("Priority for audio volume."));
			Schema.Number(TEXT("reverbVolume"), TEXT("Volume level for reverb (0.0-1.0)."));
			Schema.Object(TEXT("rotation"), TEXT("Rotation {pitch, yaw, roll}."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("pitch"), TEXT("Pitch"));
				  S.Number(TEXT("yaw"), TEXT("Yaw"));
				  S.Number(TEXT("roll"), TEXT("Roll"));
			});
			Schema.Bool(TEXT("save"), TEXT("Whether to save the level after the operation."));
			Schema.StringEnum(TEXT("setting"), { TEXT("streaming"), TEXT("streaming_distance"), TEXT("bounds"), TEXT("world_partition"), TEXT("grid_size"), TEXT("hlod_layer"), TEXT("data_layer_assignment") }, TEXT("Which configure level streaming variant to run; omit for 'streaming'."));
			Schema.String(TEXT("sourceNodeName"), TEXT("Source node name for connection."));
			Schema.String(TEXT("sourcePinName"), TEXT("Source pin name."));
			Schema.Number(TEXT("sphereRadius"), TEXT("Radius for sphere trigger volumes."));
			Schema.Number(TEXT("streamingDistance"), TEXT("Distance/radius for streaming volume."));
			Schema.String(TEXT("streamingMethod"), TEXT("Level streaming method: Blueprint, AlwaysLoaded, or Disabled."));
			Schema.String(TEXT("streamingUsage"), TEXT("Streaming volume usage mode."));
			Schema.String(TEXT("sublevelName"), TEXT("Sub-level asset name."));
			Schema.String(TEXT("sublevelPath"), TEXT("Sub-level asset path."));
			Schema.String(TEXT("targetNodeName"), TEXT("Target node name for connection."));
			Schema.String(TEXT("targetPinName"), TEXT("Target pin name."));
			Schema.Number(TEXT("terminalVelocity"), TEXT("Terminal velocity in the volume."));
			Schema.Bool(TEXT("unboundOnly"), TEXT("Remove every call-function node that has no bound function instead of a named node."));
			Schema.StringEnum(TEXT("volumeClass"), { TEXT("TriggerVolume"), TEXT("TriggerBox"), TEXT("TriggerSphere"), TEXT("TriggerCapsule"), TEXT("BlockingVolume"), TEXT("KillZVolume"), TEXT("PainCausingVolume"), TEXT("PhysicsVolume"), TEXT("AudioVolume"), TEXT("ReverbVolume"), TEXT("CullDistanceVolume"), TEXT("PrecomputedVisibilityVolume"), TEXT("LightmassImportanceVolume"), TEXT("NavMeshBoundsVolume"), TEXT("NavModifierVolume"), TEXT("CameraBlockingVolume"), TEXT("PostProcessVolume") }, TEXT("Volume class to spawn."));
			Schema.Object(TEXT("volumeExtent"), TEXT("Extent of the volume."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.Object(TEXT("volumeLocation"), TEXT("Location of the volume."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT("X"));
				  S.Number(TEXT("y"), TEXT("Y"));
				  S.Number(TEXT("z"), TEXT("Z"));
			});
			Schema.String(TEXT("volumeName"), TEXT("Volume actor name."));
			Schema.StringEnum(TEXT("volumeProperty"), { TEXT("properties"), TEXT("extent"), TEXT("bounds") }, TEXT("Which set volume properties variant to run; omit for 'properties'."));
			Schema.String(TEXT("volumeType"), TEXT("Volume type for get_volumes_info."));
			Schema.StringEnum(TEXT("action"), { TEXT("create_level_structure"), TEXT("configure_level_streaming"), TEXT("edit_level_blueprint"), TEXT("get_level_structure_info"), TEXT("create_volume"), TEXT("set_volume_properties"), TEXT("remove_volume"), TEXT("get_volumes_info") }, TEXT("Action to invoke on manage_level_structure."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};

class FMcpGenTool_ManagePcg : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_pcg"); }
	FString GetDescription() const override { return TEXT("Create, edit, execute, and configure PCG graphs: graph assets, input/sampler/filter/spawner nodes, pin connections, node settings, and partition grid size."); }
	FString GetCategory() const override { return TEXT("world"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("actorClass"), TEXT("Actor class path/name."));
			Schema.String(TEXT("actorName"), TEXT("Actor name in the level."));
			Schema.String(TEXT("assetPath"), TEXT("Canonical /Game asset path."));
			Schema.String(TEXT("classPath"), TEXT("Class path/name."));
			Schema.String(TEXT("componentName"), TEXT("Component name for PCG execution."));
			Schema.String(TEXT("componentPath"), TEXT("Component path/name for PCG execution."));
			Schema.Bool(TEXT("createComponent"), TEXT("Create a new PCG component when no selector is supplied."));
			Schema.StringEnum(TEXT("edit"), { TEXT("create"), TEXT("create_subgraph"), TEXT("connect_pins"), TEXT("set_node_settings"), TEXT("set_partition_grid_size") }, TEXT("Which edit pcg graph variant to run."));
			Schema.Bool(TEXT("force"), TEXT("Force regeneration even if a result already exists."));
			Schema.String(TEXT("graphPath"), TEXT("PCG graph asset path (e.g. /Game/PCG/PCG_MyGraph)."));
			Schema.Number(TEXT("gridSize"), TEXT("PCG partition grid cell size."));
			Schema.String(TEXT("inputName"), TEXT("PCG input pin name."));
			Schema.String(TEXT("meshPath"), TEXT("Canonical /Game static mesh asset path."));
			Schema.String(TEXT("name"), TEXT("Name for the new asset or node."));
			Schema.String(TEXT("nodeId"), TEXT("PCG node identifier."));
			Schema.StringEnum(TEXT("nodeKind"), { TEXT("node"), TEXT("surface_sampler"), TEXT("spline_sampler"), TEXT("mesh_sampler"), TEXT("volume_sampler"), TEXT("static_mesh_spawner"), TEXT("actor_spawner"), TEXT("spline_spawner"), TEXT("density_filter"), TEXT("distance_filter"), TEXT("height_filter"), TEXT("slope_filter"), TEXT("bounds_filter"), TEXT("bounds_modifier"), TEXT("landscape_data_node"), TEXT("spline_data_node"), TEXT("actor_data_node"), TEXT("texture_data_node"), TEXT("volume_data_node"), TEXT("transform_points"), TEXT("copy_points"), TEXT("merge_points"), TEXT("project_to_surface"), TEXT("self_pruning") }, TEXT("Which add pcg node variant to run; omit for 'node'."));
			Schema.String(TEXT("nodeName"), TEXT("Level blueprint node name."));
			Schema.String(TEXT("nodeType"), TEXT("PCG node type alias or UPCGSettings class path/name."));
			Schema.String(TEXT("outputName"), TEXT("PCG output pin name."));
			Schema.Bool(TEXT("overwrite"), TEXT("Overwrite the asset when it already exists."));
			Schema.String(TEXT("parentGraphPath"), TEXT("Parent PCG graph asset path for subgraph insertion."));
			Schema.String(TEXT("path"), TEXT("Canonical /Game directory path."));
			Schema.Number(TEXT("posX"), TEXT("Node graph X position."));
			Schema.Number(TEXT("posY"), TEXT("Node graph Y position."));
			Schema.Bool(TEXT("save"), TEXT("Whether to save the level after the operation."));
			Schema.String(TEXT("scope"), TEXT("Partition grid target scope: 'world' or 'component'."));
			Schema.FreeformObject(TEXT("settings"), TEXT("UPCGSettings property key-value pairs applied by reflection."));
			Schema.String(TEXT("settingsClass"), TEXT("UPCGSettings class path/name for the PCG node."));
			Schema.String(TEXT("sourceNodeId"), TEXT("Source node identifier for pin connection."));
			Schema.String(TEXT("sourcePin"), TEXT("Source pin name."));
			Schema.String(TEXT("subgraphPath"), TEXT("PCG subgraph asset path used by subgraph nodes."));
			Schema.String(TEXT("targetNodeId"), TEXT("Target node identifier for pin connection."));
			Schema.String(TEXT("targetPin"), TEXT("Target pin name."));
			Schema.String(TEXT("texturePath"), TEXT("Canonical /Game texture asset path."));
			Schema.String(TEXT("title"), TEXT("Node title (alias of nodeName)."));
			Schema.Number(TEXT("x"), TEXT("Node graph X position (alias of posX)."));
			Schema.Number(TEXT("y"), TEXT("Node graph Y position (alias of posY)."));
			Schema.StringEnum(TEXT("action"), { TEXT("edit_pcg_graph"), TEXT("add_pcg_node"), TEXT("execute_pcg_graph") }, TEXT("Action to invoke on manage_pcg."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedWorld_StructureCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ManageLevelStructure());

	Registry.Register(new FMcpGenTool_ManagePcg());

}
