// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"


void FMcpGeneratedParentRegistry::RegisterAll()

{

	RegisterGeneratedCore_ActorCapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedCore_AssetCapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedCore_BlueprintCapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedCore_SystemCapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedGameplay_AICapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedGameplay_AnimCapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedGameplay_CombatCapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedGameplay_SysCapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedWorld_EnvironmentCapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedWorld_GeometryCapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedWorld_StructureCapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedUtility_AudioCapabilities(FMcpToolRegistry::Get());

	RegisterGeneratedUtility_SequenceCapabilities(FMcpToolRegistry::Get());

}


namespace

{

	struct FRegisterGeneratedParentTools
	{
		FRegisterGeneratedParentTools()
		{
			FMcpGeneratedParentRegistry::RegisterAll();
		}
	};

	static FRegisterGeneratedParentTools GRegisterGeneratedParentTools;

}
