// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_BuildEnvironment : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("build_environment"); }
	FString GetDescription() const override { return TEXT("Build environments: landscapes, foliage, procedural terrain/biomes, lighting setups, spline roads/rivers/fences, and world decoration."); }
	FString GetCategory() const override { return TEXT("world"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
		McpGeneratedParentSchema::AppendBuildEnvironmentFields(Schema);
		McpGeneratedParentSchema::AppendBuildEnvironmentStructures(Schema);
			Schema.StringEnum(TEXT("action"), { TEXT("create_landscape"), TEXT("sculpt"), TEXT("edit_landscape"), TEXT("export_heightmap"), TEXT("create_landscape_asset"), TEXT("add_foliage"), TEXT("get_foliage_instances"), TEXT("remove_foliage"), TEXT("paint_foliage_instances"), TEXT("create_foliage_type"), TEXT("configure_foliage"), TEXT("create_procedural_terrain"), TEXT("bake_lightmap"), TEXT("export_snapshot"), TEXT("import_snapshot"), TEXT("delete"), TEXT("create_light"), TEXT("create_sky_light"), TEXT("create_lighting_setup"), TEXT("configure_lighting"), TEXT("build_lighting"), TEXT("list_light_types"), TEXT("configure_ray_tracing"), TEXT("set_light_channel"), TEXT("configure_lightmass"), TEXT("create_capture_actor"), TEXT("configure_scene_capture"), TEXT("configure_post_process"), TEXT("create_spline"), TEXT("edit_spline"), TEXT("remove_spline_point"), TEXT("configure_spline_meshes"), TEXT("get_splines_info"), TEXT("create_atmosphere_actor"), TEXT("configure_atmosphere"), TEXT("create_weather_system"), TEXT("configure_weather"), TEXT("create_water_body"), TEXT("configure_water"), TEXT("create_buoyancy_component") }, TEXT("Action to invoke on build_environment."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedWorld_EnvironmentCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_BuildEnvironment());

}
