// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ManageSequence : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_sequence"); }
	FString GetDescription() const override { return TEXT("Edit Level Sequences, cinematic tracks, Movie Render Queue jobs, media playback assets, Take Recorder, and replay controls."); }
	FString GetCategory() const override { return TEXT("utility"); }
	bool EnforceStrictArguments() const override { return true; }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.Bool(TEXT("activate"), TEXT("Whether the key activates (true) or deactivates (false)."));
			Schema.String(TEXT("actorName"), TEXT("Actor name in the current level."));
			Schema.Array(TEXT("actorNames"), TEXT("Actor names."), TEXT("string"));
			Schema.String(TEXT("actorPath"), TEXT("Actor path (alias of actorName)."));
			Schema.Array(TEXT("actors"), TEXT("Actor names to record (alias of actorNames)."), TEXT("string"));
			Schema.Array(TEXT("additionalOptions"), TEXT("Additional replay streamer options."), TEXT("string"));
			Schema.String(TEXT("animationPath"), TEXT("Animation sequence asset path (alias of animationSequencePath)."));
			Schema.String(TEXT("animationSequencePath"), TEXT("Animation sequence asset path."));
			Schema.String(TEXT("antiAliasingMethod"), TEXT("Anti-aliasing method name, such as TSAA or FXAA."));
			Schema.Number(TEXT("aperture"), TEXT("Aperture f-stop."));
			Schema.String(TEXT("assetPath"), TEXT("Canonical /Game asset path."));
			Schema.Bool(TEXT("autoClear"), TEXT("Whether the media texture clears when playback stops."));
			Schema.Bool(TEXT("autoPlay"), TEXT("Whether the media player plays automatically on open."));
			Schema.String(TEXT("bindingGuid"), TEXT("Sequencer binding GUID (alias of bindingId)."));
			Schema.String(TEXT("bindingId"), TEXT("Sequencer binding GUID to key against."));
			Schema.Object(TEXT("burnIn"), TEXT("Burn-in settings."), [](FMcpSchemaBuilder& S) {
				  S.Bool(TEXT("enabled"), TEXT("Whether burn-ins are enabled."));
				  S.Bool(TEXT("compositeOntoFinalImage"), TEXT("Whether to composite onto the final image."));
				  S.String(TEXT("classPath"), TEXT("Burn-in widget class path."));
				  S.Required({ TEXT("enabled") });
			});
			Schema.String(TEXT("cameraActorName"), TEXT("Actor name in the current level."));
			Schema.String(TEXT("cameraName"), TEXT("Actor name in the current level."));
			Schema.String(TEXT("cameraShakeClass"), TEXT("Camera shake class path."));
			Schema.String(TEXT("cameraShakePath"), TEXT("Camera shake asset path."));
			Schema.Number(TEXT("checkpointSaveMaxMSPerFrame"), TEXT("Max checkpoint save MS per frame (<=1000)."));
			Schema.String(TEXT("className"), TEXT("Unreal class path for the spawnable."));
			Schema.Bool(TEXT("clearSources"), TEXT("Whether to clear existing Take Recorder sources first."));
			Schema.String(TEXT("componentName"), TEXT("Name of the component owning the target material."));
			Schema.FreeformObject(TEXT("consoleVariables"), TEXT("CVar name-value pairs."));
			Schema.StringEnum(TEXT("control"), { TEXT("create"), TEXT("queue"), TEXT("start"), TEXT("play"), TEXT("pause"), TEXT("seek"), TEXT("set_playback_speed"), TEXT("start_recording"), TEXT("stop_recording"), TEXT("start_killcam"), TEXT("stop") }, TEXT("Which create render job variant to run; omit for 'create'."));
			Schema.Number(TEXT("craneArmLength"), TEXT("Crane arm length."));
			Schema.Number(TEXT("cranePitch"), TEXT("Crane pitch in degrees."));
			Schema.Number(TEXT("craneYaw"), TEXT("Crane yaw in degrees."));
			Schema.Number(TEXT("currentAperture"), TEXT("Aperture as an f-stop (alias of aperture)."));
			Schema.Number(TEXT("currentFocalLength"), TEXT("Focal length in millimetres (alias of focalLength)."));
			Schema.String(TEXT("defaultSourcePath"), TEXT("Default media source asset path for a platform media source."));
			Schema.StringEnum(TEXT("deleteScope"), { TEXT("sequence"), TEXT("track") }, TEXT("Which delete variant to run; omit for 'sequence'."));
			Schema.String(TEXT("demoName"), TEXT("Demo replay name."));
			Schema.String(TEXT("destinationPath"), TEXT("Destination /Game folder for the copy."));
			Schema.Bool(TEXT("disableOthers"), TEXT("Whether non-matching recorded tracks are disabled."));
			Schema.String(TEXT("displayName"), TEXT("Shot display name (alias of shotName)."));
			Schema.Number(TEXT("duration"), TEXT("Optional max recording duration in seconds."));
			Schema.Integer(TEXT("durationFrames"), TEXT("Section duration in display-rate frames."));
			Schema.Number(TEXT("durationSeconds"), TEXT("Killcam duration in seconds (<=600)."));
			Schema.StringEnum(TEXT("edit"), { TEXT("add_actor"), TEXT("add_actors"), TEXT("add_camera"), TEXT("add_spawnable"), TEXT("remove_actors"), TEXT("add_track"), TEXT("add_section"), TEXT("add_keyframe"), TEXT("set_locked"), TEXT("set_muted"), TEXT("set_solo") }, TEXT("Which edit sequence bindings variant to run."));
			Schema.Bool(TEXT("enabled"), TEXT("Whether the matched recorded tracks are enabled."));
			Schema.Number(TEXT("end"), TEXT("Range end frame or time."));
			Schema.Integer(TEXT("endFrame"), TEXT("Custom playback range end frame, EXCLUSIVE: must be strictly greater than startFrame. 0..1 renders exactly one frame; 0..0 renders nothing and is refused as INVALID_FRAME_RANGE."));
			Schema.String(TEXT("executorClass"), TEXT("Movie pipeline executor class path."));
			Schema.String(TEXT("fileNameFormat"), TEXT("Output file name format string."));
			Schema.String(TEXT("filePath"), TEXT("File system path to a media file."));
			Schema.Array(TEXT("filePaths"), TEXT("Media file paths appended to the playlist."), TEXT("string"));
			Schema.Object(TEXT("filmback"), TEXT("Nested filmback overrides (Cameras.cpp:77-80 nested object \"filmback\")."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("sensorWidth"), TEXT("Sensor width in millimetres."));
				  S.Number(TEXT("sensorHeight"), TEXT("Sensor height in millimetres."));
			});
			Schema.Number(TEXT("focalLength"), TEXT("Focal length in mm."));
			Schema.Object(TEXT("focus"), TEXT("Nested focus overrides (Cameras.cpp:81-83 nested object \"focus\")."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("manualFocusDistance"), TEXT("Manual focus distance in centimetres."));
				  S.Number(TEXT("focusDistance"), TEXT("Manual focus distance alias in centimetres."));
			});
			Schema.Number(TEXT("focusDistance"), TEXT("Focus distance."));
			Schema.Integer(TEXT("frame"), TEXT("Frame number for the keyframe."));
			Schema.TypeUnion(TEXT("frameRate"), { TEXT("number"), TEXT("string") }, TEXT("Frame rate as fps or a rate string such as 24fps or 24000/1001."));
			Schema.String(TEXT("friendlyName"), TEXT("Human-readable replay name."));
			Schema.Number(TEXT("from"), TEXT("Fade start opacity value."));
			Schema.Integer(TEXT("height"), TEXT("Output height in pixels (positive; paired with width)."));
			Schema.Bool(TEXT("includeTranslucentObjects"), TEXT("Whether the pass includes translucent objects."));
			Schema.StringEnum(TEXT("info"), { TEXT("properties"), TEXT("bindings"), TEXT("tracks"), TEXT("track_types"), TEXT("list"), TEXT("open") }, TEXT("Which get properties variant to run; omit for 'properties'."));
			Schema.String(TEXT("jobId"), TEXT("Render job identifier."));
			Schema.String(TEXT("jobName"), TEXT("Render job name (alias of renderJobName)."));
			Schema.StringEnum(TEXT("kind"), { TEXT("cine_camera_actor"), TEXT("master_sequence"), TEXT("source"), TEXT("player"), TEXT("playlist"), TEXT("texture"), TEXT("sound_component") }, TEXT("Which create cinematic asset variant to run."));
			Schema.String(TEXT("label"), TEXT("Actor label alias for the camera or rig actor (alias of actorName)."));
			Schema.Integer(TEXT("lengthInFrames"), TEXT("Sequence length in frames."));
			Schema.Object(TEXT("lens"), TEXT("Nested lens overrides (Cameras.cpp:71-76 nested object \"lens\")."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("currentFocalLength"), TEXT("Focal length in millimetres."));
				  S.Number(TEXT("focalLength"), TEXT("Focal length alias in millimetres."));
				  S.Number(TEXT("currentAperture"), TEXT("Aperture as an f-stop."));
				  S.Number(TEXT("aperture"), TEXT("Aperture alias as an f-stop."));
			});
			Schema.Array(TEXT("levelNames"), TEXT("Level names toggled by the visibility track."), TEXT("string"));
			Schema.Bool(TEXT("loadDefaultMapOnStop"), TEXT("Whether to load the default map on stop."));
			Schema.Object(TEXT("location"), TEXT("Camera location."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT(""));
				  S.Number(TEXT("y"), TEXT(""));
				  S.Number(TEXT("z"), TEXT(""));
				  S.Required({ TEXT("x"), TEXT("y"), TEXT("z") });
			});
			Schema.Bool(TEXT("locked"), TEXT("Whether to lock."));
			Schema.Bool(TEXT("loop"), TEXT("Whether media playback loops."));
			Schema.String(TEXT("loopMode"), TEXT("Playback loop mode: once, loop, or pingpong."));
			Schema.Bool(TEXT("looping"), TEXT("Whether media playback loops (alias of loop)."));
			Schema.Number(TEXT("manualFocusDistance"), TEXT("Manual focus distance in centimetres (alias of focusDistance)."));
			Schema.String(TEXT("mapPath"), TEXT("Canonical /Game map path."));
			Schema.String(TEXT("masterSequencePath"), TEXT("Canonical /Game master sequence path."));
			Schema.Integer(TEXT("materialIndex"), TEXT("Material slot index on the component."));
			Schema.String(TEXT("materialPath"), TEXT("Material asset path for a material render pass."));
			Schema.Number(TEXT("maxRecordTimeSeconds"), TEXT("Max record time (<=86400)."));
			Schema.String(TEXT("mediaPath"), TEXT("Media file path (alias of filePath)."));
			Schema.String(TEXT("mediaPlayerPath"), TEXT("Canonical /Game media player path."));
			Schema.String(TEXT("mediaSourcePath"), TEXT("Canonical /Game media source path."));
			Schema.FreeformObject(TEXT("metadata"), TEXT("Arbitrary metadata key-value pairs."));
			Schema.String(TEXT("method"), TEXT("Anti-aliasing method (alias of antiAliasingMethod)."));
			Schema.Bool(TEXT("muted"), TEXT("Whether to mute."));
			Schema.String(TEXT("name"), TEXT("Name for the new sequence or asset."));
			Schema.String(TEXT("newName"), TEXT("New name for the sequence asset."));
			Schema.Bool(TEXT("onlyJob"), TEXT("Whether to queue only this job."));
			Schema.String(TEXT("outputDirectory"), TEXT("Output directory for rendered frames."));
			Schema.String(TEXT("parameterName"), TEXT("Material parameter name to animate."));
			Schema.String(TEXT("path"), TEXT("Canonical /Game sequence asset path."));
			Schema.Bool(TEXT("paused"), TEXT("Whether replay playback is paused."));
			Schema.FreeformObject(TEXT("platformSources"), TEXT("Per-platform media source asset paths keyed by platform name."));
			Schema.Bool(TEXT("playOnOpen"), TEXT("Whether the media player plays on open (alias of autoPlay)."));
			Schema.Integer(TEXT("playbackEnd"), TEXT("Playback end frame."));
			Schema.Number(TEXT("playbackSpeed"), TEXT("Playback speed multiplier (positive)."));
			Schema.Integer(TEXT("playbackStart"), TEXT("Playback start frame."));
			Schema.String(TEXT("playerPath"), TEXT("Canonical /Game media player path."));
			Schema.Integer(TEXT("playlistIndex"), TEXT("Zero-based index into the media playlist."));
			Schema.String(TEXT("playlistPath"), TEXT("Canonical /Game media playlist path."));
			Schema.Number(TEXT("positionOnRail"), TEXT("Position on the rail (0-1)."));
			Schema.Bool(TEXT("precacheFile"), TEXT("Whether the file media source precaches on open."));
			Schema.Bool(TEXT("prioritizeActors"), TEXT("Whether to prioritize actor replication during recording."));
			Schema.Array(TEXT("properties"), TEXT("Recorded property names (alias of tracks)."), TEXT("string"));
			Schema.String(TEXT("property"), TEXT("Property name to keyframe (Transform, Location, Rotation, Scale)."));
			Schema.String(TEXT("propertyName"), TEXT("Property name to animate (alias of property)."));
			Schema.String(TEXT("propertyPath"), TEXT("Nested property path to animate."));
			Schema.String(TEXT("propertyType"), TEXT("Property value type hint (alias of type)."));
			Schema.Bool(TEXT("recordInto"), TEXT("Whether to record into the supplied sequence rather than a new take."));
			Schema.Bool(TEXT("recordParentHierarchy"), TEXT("Whether the source records its parent hierarchy."));
			Schema.String(TEXT("recordType"), TEXT("Take recording source type."));
			Schema.String(TEXT("recordingSequencePath"), TEXT("Canonical /Game recording sequence path."));
			Schema.Bool(TEXT("reduceKeys"), TEXT("Whether to reduce keyframes."));
			Schema.String(TEXT("renderJobId"), TEXT("Render job identifier (alias of jobId)."));
			Schema.String(TEXT("renderJobName"), TEXT("Name for the render job."));
			Schema.String(TEXT("renderPass"), TEXT("Render pass identifier, such as beauty or object_id."));
			Schema.Array(TEXT("renderPasses"), TEXT("Render pass identifiers to add."), TEXT("string"));
			Schema.String(TEXT("replayName"), TEXT("Name for the demo replay."));
			Schema.TypeUnion(TEXT("resolution"), { TEXT("number"), TEXT("string") }, TEXT("Output resolution in WIDTHxHEIGHT format, such as 1920x1080."));
			Schema.Object(TEXT("rotation"), TEXT("Camera rotation as {pitch, yaw, roll} (x/y/z are accepted as aliases)."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("pitch"), TEXT(""));
				  S.Number(TEXT("yaw"), TEXT(""));
				  S.Number(TEXT("roll"), TEXT(""));
				  S.Number(TEXT("x"), TEXT(""));
				  S.Number(TEXT("y"), TEXT(""));
				  S.Number(TEXT("z"), TEXT(""));
			});
			Schema.Integer(TEXT("rowIndex"), TEXT("Sequencer row index for the created section."));
			Schema.Bool(TEXT("save"), TEXT("Whether to save the sequence asset after the mutation."));
			Schema.Number(TEXT("seconds"), TEXT("Seek time in seconds (alias of timeSeconds)."));
			Schema.Integer(TEXT("sectionIndex"), TEXT("Index of the shot section to configure."));
			Schema.String(TEXT("sectionName"), TEXT("Shot section display name to configure (alternative to sectionIndex)."));
			Schema.Number(TEXT("seekTime"), TEXT("Seek time in seconds."));
			Schema.Number(TEXT("sensorHeight"), TEXT("Sensor height in mm."));
			Schema.Number(TEXT("sensorWidth"), TEXT("Sensor width in mm."));
			Schema.StringEnum(TEXT("sequenceOp"), { TEXT("create"), TEXT("duplicate"), TEXT("rename") }, TEXT("Which create variant to run; omit for 'create'."));
			Schema.String(TEXT("sequencePath"), TEXT("Canonical /Game sequence asset path."));
			Schema.StringEnum(TEXT("sequenceProperty"), { TEXT("properties"), TEXT("display_rate"), TEXT("tick_resolution"), TEXT("playback_speed"), TEXT("view_range"), TEXT("work_range") }, TEXT("Which set properties variant to run; omit for 'properties'."));
			Schema.StringEnum(TEXT("setting"), { TEXT("camera"), TEXT("rig_crane"), TEXT("rig_rail"), TEXT("shot"), TEXT("demo"), TEXT("killcam_duration"), TEXT("output"), TEXT("anti_aliasing"), TEXT("add_render_pass"), TEXT("burn_ins"), TEXT("console_variables"), TEXT("sources"), TEXT("recorded_tracks"), TEXT("panel"), TEXT("start_recording"), TEXT("stop_recording") }, TEXT("Which configure cinematic variant to run."));
			Schema.Object(TEXT("settings"), TEXT("Nested MRQ settings."), [](FMcpSchemaBuilder& S) {
				  S.Integer(TEXT("handleFrameCount"), TEXT("Handle frame count clamped to >= 0."));
				  S.Integer(TEXT("zeroPadFrameNumbers"), TEXT("Zero-padding width for frame numbers."));
				  S.Integer(TEXT("spatialSampleCount"), TEXT("Spatial sample count per render sample pass."));
				  S.Integer(TEXT("temporalSampleCount"), TEXT("Temporal sample count per render sample pass."));
				  S.String(TEXT("antiAliasingMethod"), TEXT("Anti-aliasing method name, such as TSAA or FXAA."));
				  S.String(TEXT("method"), TEXT("Anti-aliasing method alias."));
			});
			Schema.String(TEXT("shotName"), TEXT("Name for the new sequence or asset."));
			Schema.String(TEXT("shotSequencePath"), TEXT("Canonical /Game shot sequence path."));
			Schema.String(TEXT("skeletalMeshPath"), TEXT("Skeletal mesh asset path."));
			Schema.Bool(TEXT("solo"), TEXT("Whether to solo."));
			Schema.Array(TEXT("sourceActors"), TEXT("Actor names."), TEXT("string"));
			Schema.Array(TEXT("sourceClasses"), TEXT("Take Recorder source class paths."), TEXT("string"));
			Schema.String(TEXT("sourcePath"), TEXT("Source file or asset path."));
			Schema.Array(TEXT("sourcePaths"), TEXT("Media source asset paths for the playlist."), TEXT("string"));
			Schema.String(TEXT("sourceType"), TEXT("Media source type: file, stream, or platform."));
			Schema.Integer(TEXT("spatialSampleCount"), TEXT("Sample count per render sample pass."));
			Schema.Bool(TEXT("spawnable"), TEXT("Whether to add as spawnable."));
			Schema.Number(TEXT("speed"), TEXT("Playback speed multiplier (positive)."));
			Schema.Number(TEXT("start"), TEXT("Range start frame or time."));
			Schema.Integer(TEXT("startFrame"), TEXT("Custom playback range start frame (paired with endFrame)."));
			Schema.Number(TEXT("startTime"), TEXT("Range start frame or time."));
			Schema.String(TEXT("streamUrl"), TEXT("URL for a stream media source."));
			Schema.String(TEXT("subsequencePath"), TEXT("Canonical /Game subsequence path."));
			Schema.String(TEXT("takePresetPath"), TEXT("Canonical /Game take preset path."));
			Schema.String(TEXT("takeSequencePath"), TEXT("Canonical /Game take sequence path."));
			Schema.String(TEXT("targetActor"), TEXT("Actor receiving the media sound component (alias of actorName)."));
			Schema.Integer(TEXT("temporalSampleCount"), TEXT("Sample count per render sample pass."));
			Schema.Number(TEXT("time"), TEXT("Seek time in seconds (alias of timeSeconds)."));
			Schema.Number(TEXT("timeSeconds"), TEXT("Seek time in seconds (<=86400)."));
			Schema.Number(TEXT("to"), TEXT("Fade end opacity value."));
			Schema.StringEnum(TEXT("trackKind"), { TEXT("camera_cut"), TEXT("camera_shake"), TEXT("transform"), TEXT("property"), TEXT("skeletal_animation"), TEXT("material_parameter"), TEXT("particle"), TEXT("event"), TEXT("fade"), TEXT("level_visibility"), TEXT("shot"), TEXT("subsequence") }, TEXT("Which add cinematic track variant to run."));
			Schema.String(TEXT("trackName"), TEXT("Name of the track to modify."));
			Schema.Array(TEXT("trackNames"), TEXT("Recorded track names (alias of tracks)."), TEXT("string"));
			Schema.String(TEXT("trackType"), TEXT("MovieScene track type string."));
			Schema.Array(TEXT("tracks"), TEXT("Track names to record per source."), TEXT("string"));
			Schema.String(TEXT("url"), TEXT("URL to a media stream."));
			Schema.Array(TEXT("urls"), TEXT("Stream URLs appended to the playlist."), TEXT("string"));
			Schema.Bool(TEXT("useCurrentLevel"), TEXT("Whether to render against the currently loaded level."));
			Schema.AnyValue(TEXT("value"), TEXT("Keyframe value. For property \"Transform\" pass a composed object with any subset of {location:{x,y,z}, rotation:{pitch,yaw,roll}, scale:{x,y,z}}; each component supplied must carry all of its finite axes. For \"Location\"/\"Rotation\"/\"Scale\" pass that component object alone. Other properties take their own scalar value, so no type is declared here."));
			Schema.String(TEXT("visibility"), TEXT("Level visibility state: Visible or Hidden."));
			Schema.Integer(TEXT("width"), TEXT("Output width in pixels (positive; paired with height)."));
			Schema.StringEnum(TEXT("action"), { TEXT("create"), TEXT("get_properties"), TEXT("delete"), TEXT("play"), TEXT("set_properties"), TEXT("edit_sequence_bindings"), TEXT("edit_sequence_tracks"), TEXT("get_metadata"), TEXT("set_metadata"), TEXT("create_cinematic_asset"), TEXT("add_cinematic_track"), TEXT("configure_cinematic"), TEXT("create_render_job"), TEXT("configure_render_job"), TEXT("create_media_asset"), TEXT("play_media"), TEXT("configure_take_recorder"), TEXT("play_demo"), TEXT("configure_demo_settings") }, TEXT("Action to invoke on manage_sequence."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedUtility_SequenceCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ManageSequence());

}
