// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ManageCombat : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_combat"); }
	FString GetDescription() const override { return TEXT("Create weapons with hitscan/projectile firing, configure damage types, hitboxes, reload, and melee combat (combos, parry, block)."); }
	FString GetCategory() const override { return TEXT("gameplay"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.Bool(TEXT("adsEnabled"), TEXT("Enable aim-down-sights."));
			Schema.Number(TEXT("adsFov"), TEXT("Field of view while aiming."));
			Schema.Number(TEXT("adsSpeed"), TEXT("Time in seconds to reach full aim."));
			Schema.Number(TEXT("adsSpreadMultiplier"), TEXT("Spread multiplier applied while aiming."));
			Schema.Number(TEXT("ammoPerShot"), TEXT("Ammo consumed per shot."));
			Schema.String(TEXT("ammoType"), TEXT("Ammo type identifier."));
			Schema.Number(TEXT("armorValue"), TEXT("Armor value written to the Blueprint."));
			Schema.ArrayOfObjects(TEXT("attachmentSlots"), TEXT("Attachment slot definitions created on the weapon."), [](FMcpSchemaBuilder& S) {
				  S.String(TEXT("slotName"), TEXT("Slot identifier."));
				  S.String(TEXT("socketName"), TEXT("Socket the attachment binds to."));
				  S.Array(TEXT("allowedTypes"), TEXT("Attachment types accepted by this slot."), TEXT("string"));
			});
			Schema.Number(TEXT("baseDamage"), TEXT("Base damage per shot."));
			Schema.Number(TEXT("blockDamageReduction"), TEXT("Damage reduction while blocking (0-1)."));
			Schema.Number(TEXT("blockStaminaCost"), TEXT("Stamina consumed per blocked hit."));
			Schema.String(TEXT("blueprintPath"), TEXT("Canonical /Game Blueprint asset path."));
			Schema.Bool(TEXT("bounceEnabled"), TEXT("Enable projectile bouncing on impact."));
			Schema.Number(TEXT("bounceVelocityRatio"), TEXT("Fraction of velocity retained on bounce (0-1)."));
			Schema.Number(TEXT("collisionRadius"), TEXT("Projectile collision sphere radius."));
			Schema.Number(TEXT("comboWindowTime"), TEXT("Seconds the combo input window stays open."));
			Schema.Number(TEXT("criticalMultiplier"), TEXT("Critical hit damage multiplier."));
			Schema.Number(TEXT("damageAmount"), TEXT("Damage amount written to the Blueprint."));
			Schema.Number(TEXT("damageImpulse"), TEXT("Physics impulse applied on hit."));
			Schema.Number(TEXT("damageMultiplier"), TEXT("Damage multiplier applied for this hitbox."));
			Schema.Number(TEXT("damagePerSecond"), TEXT("Damage applied per second by the effect."));
			Schema.Number(TEXT("damageReduction"), TEXT("Fraction of incoming damage mitigated by armor (0-1)."));
			Schema.String(TEXT("damageType"), TEXT("Damage type name written to the Blueprint."));
			Schema.Number(TEXT("duration"), TEXT("Duration in seconds."));
			Schema.String(TEXT("effectType"), TEXT("Damage effect classifier, for example DamageOverTime."));
			Schema.String(TEXT("ejectionSocketName"), TEXT("Socket name used as the shell ejection point."));
			Schema.String(TEXT("equipAnimationPath"), TEXT("Canonical /Game equip montage path."));
			Schema.Number(TEXT("fireRate"), TEXT("Rate of fire in rounds per minute."));
			Schema.Number(TEXT("headshotMultiplier"), TEXT("Headshot damage multiplier."));
			Schema.Number(TEXT("healAmount"), TEXT("Heal amount written to the Blueprint."));
			Schema.Number(TEXT("hitPauseDuration"), TEXT("Hitstop duration in seconds."));
			Schema.Number(TEXT("hitPauseTimeDilation"), TEXT("Time dilation applied during hitstop."));
			Schema.String(TEXT("hitReactionMontage"), TEXT("Canonical /Game hit reaction montage path."));
			Schema.Number(TEXT("hitReactionStunTime"), TEXT("Stun duration in seconds after a hit."));
			Schema.String(TEXT("hitboxBoneName"), TEXT("Bone the hitbox is attached to."));
			Schema.Object(TEXT("hitboxSize"), TEXT("Hitbox dimensions: extent for Box, radius/halfHeight for Sphere and Capsule."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("radius"), TEXT("Sphere or capsule radius."));
				  S.Number(TEXT("halfHeight"), TEXT("Capsule half height."));
				  S.Object(TEXT("extent"), TEXT("Box half extent."), [](FMcpSchemaBuilder& S) {
				  	  S.Number(TEXT("x"), TEXT("Half extent along X."));
				  	  S.Number(TEXT("y"), TEXT("Half extent along Y."));
				  	  S.Number(TEXT("z"), TEXT("Half extent along Z."));
				  });
			});
			Schema.StringEnum(TEXT("hitboxType"), { TEXT("Capsule"), TEXT("Box"), TEXT("Sphere") }, TEXT("Hitbox collision shape."));
			Schema.Bool(TEXT("hitscanEnabled"), TEXT("Enable instant-hit (hitscan) firing."));
			Schema.Number(TEXT("homingAcceleration"), TEXT("Homing turn acceleration."));
			Schema.Bool(TEXT("homingEnabled"), TEXT("Enable homing behaviour."));
			Schema.String(TEXT("impactDecalPath"), TEXT("Canonical /Game impact decal path."));
			Schema.String(TEXT("impactParticlePath"), TEXT("Canonical /Game impact particle path."));
			Schema.String(TEXT("impactSoundPath"), TEXT("Canonical /Game impact sound path."));
			Schema.Bool(TEXT("infiniteAmmo"), TEXT("Skip ammo consumption entirely."));
			Schema.StringEnum(TEXT("info"), { TEXT("info"), TEXT("stats") }, TEXT("Which get combat info variant to run; omit for 'info'."));
			Schema.Bool(TEXT("isDamageZoneHead"), TEXT("Mark this hitbox as a headshot zone."));
			Schema.StringEnum(TEXT("kind"), { TEXT("weapon_blueprint"), TEXT("projectile_blueprint"), TEXT("damage_type"), TEXT("damage_type_setup"), TEXT("damage_effect") }, TEXT("Which create combat asset variant to run."));
			Schema.Number(TEXT("magazineSize"), TEXT("Rounds per magazine."));
			Schema.Number(TEXT("maxAmmo"), TEXT("Maximum carried ammo."));
			Schema.Number(TEXT("maxComboCount"), TEXT("Maximum number of chained combo hits."));
			Schema.Number(TEXT("maxHealth"), TEXT("Maximum health written to the Blueprint."));
			Schema.Number(TEXT("maxShield"), TEXT("Maximum shield value."));
			Schema.String(TEXT("meleeTraceEndSocket"), TEXT("Socket where the melee sweep ends."));
			Schema.Number(TEXT("meleeTraceRadius"), TEXT("Melee sphere sweep radius."));
			Schema.String(TEXT("meleeTraceStartSocket"), TEXT("Socket where the melee sweep starts."));
			Schema.String(TEXT("muzzleFlashParticlePath"), TEXT("Canonical /Game muzzle flash particle path."));
			Schema.Number(TEXT("muzzleFlashScale"), TEXT("Muzzle flash scale multiplier."));
			Schema.String(TEXT("muzzleSocketName"), TEXT("Socket name used as the muzzle attach point."));
			Schema.String(TEXT("muzzleSoundPath"), TEXT("Canonical /Game firing sound path."));
			Schema.String(TEXT("name"), TEXT("Name for the created asset or actor."));
			Schema.String(TEXT("parryAnimationPath"), TEXT("Canonical /Game parry animation path."));
			Schema.Number(TEXT("parryWindowEnd"), TEXT("Normalized parry window end (0-1)."));
			Schema.Number(TEXT("parryWindowStart"), TEXT("Normalized parry window start (0-1)."));
			Schema.String(TEXT("path"), TEXT("Canonical /Game output path for the created asset."));
			Schema.String(TEXT("projectileClass"), TEXT("Class path of the projectile the weapon spawns."));
			Schema.Number(TEXT("projectileGravityScale"), TEXT("Gravity scale applied to the projectile."));
			Schema.Number(TEXT("projectileLifespan"), TEXT("Projectile lifetime in seconds."));
			Schema.String(TEXT("projectileMeshPath"), TEXT("Canonical /Game projectile mesh path."));
			Schema.Number(TEXT("projectileSpeed"), TEXT("Projectile launch/travel speed."));
			Schema.Number(TEXT("range"), TEXT("Effective weapon range in world units."));
			Schema.Number(TEXT("recoilPitch"), TEXT("Vertical recoil per shot in degrees."));
			Schema.Number(TEXT("recoilRecovery"), TEXT("Recoil recovery speed."));
			Schema.Number(TEXT("recoilYaw"), TEXT("Horizontal recoil per shot in degrees."));
			Schema.String(TEXT("reloadAnimationPath"), TEXT("Canonical /Game reload animation montage path."));
			Schema.Number(TEXT("reloadTime"), TEXT("Reload duration in seconds."));
			Schema.StringEnum(TEXT("setting"), { TEXT("execution"), TEXT("hit_detection"), TEXT("hitbox"), TEXT("hit_reaction"), TEXT("impact_effects"), TEXT("combo"), TEXT("hit_pause"), TEXT("melee_trace"), TEXT("parry_block"), TEXT("shield"), TEXT("armor"), TEXT("apply"), TEXT("heal"), TEXT("projectile"), TEXT("movement"), TEXT("collision"), TEXT("homing"), TEXT("weapon_mesh"), TEXT("weapon_sockets"), TEXT("hitscan"), TEXT("spread_pattern"), TEXT("recoil_pattern"), TEXT("aim_down_sights"), TEXT("muzzle_flash"), TEXT("tracer"), TEXT("shell_ejection"), TEXT("weapon_trails"), TEXT("stats"), TEXT("ammo"), TEXT("reload"), TEXT("attachments"), TEXT("switching") }, TEXT("Which configure damage variant to run."));
			Schema.Number(TEXT("shellEjectionForce"), TEXT("Impulse applied to ejected shells."));
			Schema.Number(TEXT("shellLifespan"), TEXT("Shell casing lifetime in seconds."));
			Schema.String(TEXT("shellMeshPath"), TEXT("Canonical /Game shell casing mesh path."));
			Schema.Number(TEXT("shieldAmount"), TEXT("Starting shield value."));
			Schema.Number(TEXT("shieldRegenDelay"), TEXT("Seconds before shield regeneration starts."));
			Schema.Number(TEXT("shieldRegenRate"), TEXT("Shield regenerated per second."));
			Schema.Number(TEXT("spread"), TEXT("Base spread cone in degrees."));
			Schema.Number(TEXT("spreadIncrease"), TEXT("Spread added per shot."));
			Schema.StringEnum(TEXT("spreadPattern"), { TEXT("Random"), TEXT("Fixed"), TEXT("FixedWithRandom"), TEXT("Shotgun") }, TEXT("Spread pattern type."));
			Schema.Number(TEXT("spreadRecovery"), TEXT("Spread recovery rate per second."));
			Schema.Number(TEXT("startingAmmo"), TEXT("Ammo carried at spawn."));
			Schema.Number(TEXT("switchInTime"), TEXT("Time in seconds to equip the weapon."));
			Schema.Number(TEXT("switchOutTime"), TEXT("Time in seconds to unequip the weapon."));
			Schema.StringEnum(TEXT("traceChannel"), { TEXT("Visibility"), TEXT("Camera"), TEXT("Weapon"), TEXT("Custom") }, TEXT("Trace channel used for hitscan."));
			Schema.String(TEXT("tracerParticlePath"), TEXT("Canonical /Game tracer particle path."));
			Schema.Number(TEXT("tracerSpeed"), TEXT("Tracer travel speed."));
			Schema.String(TEXT("unequipAnimationPath"), TEXT("Canonical /Game unequip montage path."));
			Schema.String(TEXT("weaponMeshPath"), TEXT("Canonical /Game weapon static or skeletal mesh path."));
			Schema.String(TEXT("weaponTrailEndSocket"), TEXT("Socket where the weapon trail ends."));
			Schema.String(TEXT("weaponTrailParticlePath"), TEXT("Canonical /Game weapon trail particle path."));
			Schema.String(TEXT("weaponTrailStartSocket"), TEXT("Socket where the weapon trail starts."));
			Schema.StringEnum(TEXT("action"), { TEXT("create_combat_asset"), TEXT("configure_weapon"), TEXT("configure_projectile"), TEXT("configure_damage"), TEXT("get_combat_info") }, TEXT("Action to invoke on manage_combat."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};

class FMcpGenTool_ManageEffect : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_effect"); }
	FString GetDescription() const override { return TEXT("Niagara particle systems, VFX, debug shapes, and GPU simulations. Create systems, emitters, modules, and control particle effects."); }
	FString GetCategory() const override { return TEXT("gameplay"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.Object(TEXT("acceleration"), TEXT("Constant acceleration vector applied to particles."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT(""));
				  S.Number(TEXT("y"), TEXT(""));
				  S.Number(TEXT("z"), TEXT(""));
			});
			Schema.String(TEXT("actorName"), TEXT("Target actor name in the current level."));
			Schema.String(TEXT("assetPath"), TEXT("Canonical /Game asset path."));
			Schema.String(TEXT("attachToActor"), TEXT("Name of the actor the spawned system attaches to."));
			Schema.Bool(TEXT("autoConnect"), TEXT("Whether inserted pins are auto-connected."));
			Schema.Number(TEXT("burstCount"), TEXT("Particle count emitted per burst."));
			Schema.Number(TEXT("burstTime"), TEXT("Normalized emitter time at which the burst fires."));
			Schema.Number(TEXT("cameraOffset"), TEXT("Camera-relative offset distance."));
			Schema.StringEnum(TEXT("cleanupTarget"), { TEXT("effects"), TEXT("debug_shapes") }, TEXT("Which cleanup variant to run; omit for 'effects'."));
			Schema.String(TEXT("collisionMode"), TEXT("Particle collision mode."));
			Schema.AnyValue(TEXT("color"), TEXT("Color as an {r,g,b,a} object or an [r, g, b, a] array."));
			Schema.String(TEXT("colorMode"), TEXT("Color module mode."));
			Schema.StringEnum(TEXT("control"), { TEXT("activate"), TEXT("deactivate"), TEXT("reset"), TEXT("effect") }, TEXT("Which activate variant to run; omit for 'activate'."));
			Schema.Number(TEXT("count"), TEXT("Count value."));
			Schema.Number(TEXT("deltaTime"), TEXT("Simulation delta time per step, in seconds."));
			Schema.Number(TEXT("density"), TEXT("Volumetric fog density."));
			Schema.Bool(TEXT("deterministicEnabled"), TEXT("Whether deterministic GPU simulation is enabled."));
			Schema.Bool(TEXT("dieOnCollision"), TEXT("Whether particles are destroyed on collision."));
			Schema.Number(TEXT("duration"), TEXT("Duration in seconds."));
			Schema.String(TEXT("dynamicInputScriptPath"), TEXT("Canonical /Niagara dynamic input script path."));
			Schema.StringEnum(TEXT("edit"), { TEXT("add_emitter"), TEXT("add_user_parameter"), TEXT("bind_parameter"), TEXT("set_parameter_value"), TEXT("set_parameter"), TEXT("set_dynamic_input"), TEXT("set_emitter_properties"), TEXT("configure_event_payload"), TEXT("enable_gpu_simulation"), TEXT("connect_pins") }, TEXT("Which edit niagara system variant to run."));
			Schema.String(TEXT("emitter"), TEXT("Emitter name; alias normalized to emitterName."));
			Schema.String(TEXT("emitterName"), TEXT("Emitter name within the target Niagara system."));
			Schema.String(TEXT("emitterPath"), TEXT("Canonical /Game asset path."));
			Schema.FreeformObject(TEXT("emitterProperties"), TEXT("Emitter property key-value pairs applied by reflection."));
			Schema.String(TEXT("eventName"), TEXT("Niagara event name."));
			Schema.ArrayOfObjects(TEXT("eventPayload"), TEXT("Event payload attribute descriptors as [{ name, type }]."), [](FMcpSchemaBuilder& S) {
				  S.String(TEXT("name"), TEXT(""));
				  S.String(TEXT("type"), TEXT(""));
			});
			Schema.Number(TEXT("eventSpawnCount"), TEXT("Particles spawned per received event."));
			Schema.String(TEXT("eventType"), TEXT("Niagara event generator type (Location, Death, Collision)."));
			Schema.Number(TEXT("extinction"), TEXT("Volumetric fog extinction scale."));
			Schema.String(TEXT("filter"), TEXT("Actor name prefix selecting which transient effects are cleaned up."));
			Schema.Bool(TEXT("fixedBoundsEnabled"), TEXT("Whether fixed system bounds are enabled."));
			Schema.Number(TEXT("forceStrength"), TEXT("Force magnitude applied to particles."));
			Schema.String(TEXT("forceType"), TEXT("Force module type (Gravity, Drag, Wind, Curl, Vortex, PointAttraction)."));
			Schema.Number(TEXT("friction"), TEXT("Collision friction coefficient."));
			Schema.StringEnum(TEXT("info"), { TEXT("info"), TEXT("validate") }, TEXT("Which get niagara info variant to run; omit for 'info'."));
			Schema.String(TEXT("inputName"), TEXT("Module input name receiving the dynamic input."));
			Schema.Number(TEXT("intensity"), TEXT("Light intensity."));
			Schema.StringEnum(TEXT("interfaceKind"), { TEXT("static_mesh"), TEXT("skeletal_mesh"), TEXT("spline"), TEXT("collision_query"), TEXT("audio_spectrum") }, TEXT("Which add niagara data interface variant to run."));
			Schema.String(TEXT("killCondition"), TEXT("Expression deciding when particles are killed."));
			Schema.StringEnum(TEXT("kind"), { TEXT("niagara_system"), TEXT("niagara_emitter"), TEXT("niagara_ribbon"), TEXT("particle_trail"), TEXT("impact"), TEXT("environment"), TEXT("volumetric_fog"), TEXT("niagara"), TEXT("particle") }, TEXT("Which create effect variant to run."));
			Schema.Number(TEXT("lifetime"), TEXT("Particle lifetime in seconds."));
			Schema.Number(TEXT("lightRadius"), TEXT("Per-particle light radius."));
			Schema.String(TEXT("lightType"), TEXT("Dynamic light type (Point, Spot, Directional, Rect)."));
			Schema.Array(TEXT("location"), TEXT("World or relative location as [x, y, z]."), TEXT("number"));
			Schema.Number(TEXT("mass"), TEXT("Mass value."));
			Schema.String(TEXT("materialPath"), TEXT("Canonical /Game material asset path for the renderer."));
			Schema.String(TEXT("meshPath"), TEXT("Canonical /Game mesh asset path."));
			Schema.StringEnum(TEXT("moduleKind"), { TEXT("module"), TEXT("spawn_rate"), TEXT("spawn_burst"), TEXT("spawn_per_unit"), TEXT("initialize_particle"), TEXT("velocity"), TEXT("acceleration"), TEXT("force"), TEXT("color"), TEXT("size"), TEXT("collision"), TEXT("kill_particles"), TEXT("camera_offset"), TEXT("particle_state"), TEXT("sprite_renderer"), TEXT("mesh_renderer"), TEXT("ribbon_renderer"), TEXT("light_renderer"), TEXT("simulation_stage"), TEXT("event_generator"), TEXT("event_receiver") }, TEXT("Which add niagara module variant to run; omit for 'module'."));
			Schema.String(TEXT("moduleName"), TEXT("Module (function call) name that owns inputName; alternative to targetNodeId."));
			Schema.String(TEXT("modulePath"), TEXT("Canonical /Niagara module script path to insert."));
			Schema.String(TEXT("name"), TEXT("Name for the created asset or actor."));
			Schema.String(TEXT("nodeId"), TEXT("Niagara graph node identifier."));
			Schema.String(TEXT("parameterName"), TEXT("Niagara parameter name."));
			Schema.String(TEXT("parameterType"), TEXT("Niagara parameter type (Float, Vector, Color, ...)."));
			Schema.AnyValue(TEXT("parameterValue"), TEXT("Niagara parameter value (any type)."));
			Schema.String(TEXT("path"), TEXT("Canonical /Game output path for the created asset."));
			Schema.String(TEXT("preset"), TEXT("Particle preset name or canonical /Game particle asset path."));
			Schema.Number(TEXT("radius"), TEXT("Radius in world units."));
			Schema.Bool(TEXT("replaceExisting"), TEXT("Whether an existing dynamic input is replaced."));
			Schema.Bool(TEXT("reset"), TEXT("Whether the effect restarts from its initial state."));
			Schema.Number(TEXT("restitution"), TEXT("Collision restitution (bounciness)."));
			Schema.Bool(TEXT("save"), TEXT("Persist the created/modified asset to disk."));
			Schema.String(TEXT("savePath"), TEXT("Canonical /Game directory for the created asset."));
			Schema.Number(TEXT("scattering"), TEXT("Volumetric fog scattering distribution."));
			Schema.String(TEXT("scriptType"), TEXT("Niagara script usage (System, Emitter, Particle)."));
			Schema.String(TEXT("shape"), TEXT("String parameter."));
			Schema.String(TEXT("shapeType"), TEXT("Debug shape type (Sphere, Box, Line, Capsule)."));
			Schema.String(TEXT("sizeMode"), TEXT("Sprite size mode."));
			Schema.String(TEXT("sourceBinding"), TEXT("Data source the parameter binds to."));
			Schema.Bool(TEXT("spawnOnEvent"), TEXT("Whether the receiver spawns particles on each event."));
			Schema.Number(TEXT("spawnPerUnit"), TEXT("Particles spawned per unit of movement."));
			Schema.Number(TEXT("spawnRate"), TEXT("Particles spawned per second."));
			Schema.String(TEXT("stageIterationSource"), TEXT("Simulation stage iteration source."));
			Schema.String(TEXT("stageName"), TEXT("Simulation stage name."));
			Schema.Number(TEXT("steps"), TEXT("Number of simulation steps to advance."));
			Schema.String(TEXT("system"), TEXT("Niagara system path; alias normalized to systemPath."));
			Schema.String(TEXT("systemName"), TEXT("Runtime Niagara system/component name on the target actor."));
			Schema.String(TEXT("systemPath"), TEXT("Canonical /Game Niagara System asset path."));
			Schema.String(TEXT("targetNodeId"), TEXT("Niagara graph node the dynamic input is attached to."));
			Schema.Number(TEXT("uniformSize"), TEXT("Uniform sprite size."));
			Schema.AnyValue(TEXT("value"), TEXT("Property value (any type)."));
			Schema.String(TEXT("velocityMode"), TEXT("Velocity module mode (Linear, Cone, FromPoint)."));
			Schema.StringEnum(TEXT("action"), { TEXT("create_effect"), TEXT("debug_shape"), TEXT("spawn_niagara"), TEXT("create_dynamic_light"), TEXT("activate"), TEXT("advance_simulation"), TEXT("add_niagara_module"), TEXT("edit_niagara_system"), TEXT("remove_niagara_node"), TEXT("cleanup"), TEXT("list_debug_shapes"), TEXT("add_niagara_data_interface"), TEXT("get_niagara_info") }, TEXT("Action to invoke on manage_effect."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedGameplay_CombatCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ManageCombat());

	Registry.Register(new FMcpGenTool_ManageEffect());

}
