// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ManageGas : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_gas"); }
	FString GetDescription() const override { return TEXT("Create Gameplay Abilities, Effects, Attribute Sets, and Gameplay Cues for ability systems."); }
	FString GetCategory() const override { return TEXT("gameplay"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("abilityClass"), TEXT("GameplayAbility class path; accepted wherever abilityPath is."));
			Schema.Number(TEXT("abilityLevel"), TEXT("Level the ability is granted at."));
			Schema.String(TEXT("abilityPath"), TEXT("Canonical /Game gameplay ability asset path."));
			Schema.Array(TEXT("abilityTags"), TEXT("Gameplay tags granted to this ability."), TEXT("string"));
			Schema.Array(TEXT("activationBlockedTags"), TEXT("Tags that block activation of this ability."), TEXT("string"));
			Schema.StringEnum(TEXT("activationPolicy"), { TEXT("OnInputPressed"), TEXT("WhileInputActive"), TEXT("OnSpawn"), TEXT("OnGiven") }, TEXT("When the ability activates."));
			Schema.Array(TEXT("activationRequiredTags"), TEXT("Tags required to activate this ability."), TEXT("string"));
			Schema.String(TEXT("actorPath"), TEXT("Canonical /Game actor Blueprint path; accepted wherever blueprintPath is."));
			Schema.Number(TEXT("aoeRadius"), TEXT("Area-of-effect radius in world units."));
			Schema.Array(TEXT("applicationRequiredTags"), TEXT("Tags required to apply this effect."), TEXT("string"));
			Schema.String(TEXT("assetPath"), TEXT("Canonical /Game asset path."));
			Schema.String(TEXT("attributeName"), TEXT("Target attribute name."));
			Schema.String(TEXT("attributeSetPath"), TEXT("Canonical /Game attribute set asset path."));
			Schema.StringEnum(TEXT("attributeType"), { TEXT("Health"), TEXT("MaxHealth"), TEXT("Mana"), TEXT("MaxMana"), TEXT("Stamina"), TEXT("MaxStamina"), TEXT("Damage"), TEXT("Armor"), TEXT("AttackPower"), TEXT("MoveSpeed"), TEXT("Custom") }, TEXT("Predefined attribute type or Custom."));
			Schema.Number(TEXT("baseValue"), TEXT("Base value for the attribute."));
			Schema.Array(TEXT("blockAbilitiesWithTag"), TEXT("Tags of abilities blocked while this is active."), TEXT("string"));
			Schema.String(TEXT("blueprintPath"), TEXT("Canonical /Game Blueprint asset path."));
			Schema.String(TEXT("calculationClass"), TEXT("String parameter."));
			Schema.String(TEXT("cameraShakePath"), TEXT("Canonical /Game camera shake asset path."));
			Schema.Array(TEXT("cancelAbilitiesWithTag"), TEXT("Tags of abilities cancelled when this activates."), TEXT("string"));
			Schema.StringEnum(TEXT("clampMode"), { TEXT("None"), TEXT("Min"), TEXT("Max"), TEXT("MinMax") }, TEXT("Attribute clamping mode."));
			Schema.String(TEXT("componentName"), TEXT("AbilitySystemComponent name (defaults to AbilitySystemComponent)."));
			Schema.String(TEXT("cooldownEffectPath"), TEXT("Canonical /Game path to the cooldown Gameplay Effect."));
			Schema.String(TEXT("costEffectPath"), TEXT("Canonical /Game path to the cost Gameplay Effect."));
			Schema.String(TEXT("cuePath"), TEXT("Canonical /Game gameplay cue asset path."));
			Schema.String(TEXT("cueTag"), TEXT("Gameplay tag string."));
			Schema.String(TEXT("cueType"), TEXT("String parameter."));
			Schema.String(TEXT("decalPath"), TEXT("Canonical /Game decal material asset path."));
			Schema.Number(TEXT("defaultValue"), TEXT("Initial value for the added attribute."));
			Schema.Number(TEXT("duration"), TEXT("Duration in seconds."));
			Schema.StringEnum(TEXT("durationType"), { TEXT("Instant"), TEXT("Infinite"), TEXT("HasDuration") }, TEXT("Effect duration type."));
			Schema.String(TEXT("effectPath"), TEXT("Canonical /Game gameplay effect asset path."));
			Schema.Array(TEXT("grantedTags"), TEXT("Tags granted while the effect is active."), TEXT("string"));
			Schema.Array(TEXT("immunityTags"), TEXT("Tags that make a target immune to this effect."), TEXT("string"));
			Schema.Number(TEXT("inputID"), TEXT("Input id bound to the granted ability; -1 leaves it unbound."));
			Schema.StringEnum(TEXT("instancingPolicy"), { TEXT("NonInstanced"), TEXT("InstancedPerActor"), TEXT("InstancedPerExecution") }, TEXT("How the ability is instanced."));
			Schema.StringEnum(TEXT("kind"), { TEXT("gameplay_ability"), TEXT("gameplay_effect"), TEXT("attribute_set"), TEXT("ability_set"), TEXT("gameplay_cue_notify"), TEXT("execution_calculation") }, TEXT("Which create gas asset variant to run."));
			Schema.StringEnum(TEXT("magnitudeCalculationType"), { TEXT("ScalableFloat"), TEXT("AttributeBased"), TEXT("SetByCaller"), TEXT("CustomCalculationClass") }, TEXT("How the modifier magnitude is calculated."));
			Schema.Number(TEXT("maxValue"), TEXT("Numeric parameter."));
			Schema.Number(TEXT("minValue"), TEXT("Numeric parameter."));
			Schema.Number(TEXT("modifierIndex"), TEXT("Zero-based index of the modifier to edit."));
			Schema.Number(TEXT("modifierMagnitude"), TEXT("Magnitude of the modifier."));
			Schema.StringEnum(TEXT("modifierOperation"), { TEXT("Add"), TEXT("Multiply"), TEXT("Divide"), TEXT("Override") }, TEXT("Modifier operation applied to the attribute."));
			Schema.String(TEXT("name"), TEXT("Name for the created asset or actor."));
			Schema.String(TEXT("particleSystemPath"), TEXT("Canonical /Game particle system asset path."));
			Schema.String(TEXT("path"), TEXT("Canonical /Game output path for the created asset."));
			Schema.Number(TEXT("period"), TEXT("Period in seconds for periodic effects."));
			Schema.Array(TEXT("removalTags"), TEXT("Tags that cause this effect to be removed."), TEXT("string"));
			Schema.StringEnum(TEXT("replicationMode"), { TEXT("Full"), TEXT("Minimal"), TEXT("Mixed") }, TEXT("ASC replication mode."));
			Schema.String(TEXT("setByCallerTag"), TEXT("Gameplay tag keying a SetByCaller magnitude."));
			Schema.String(TEXT("setName"), TEXT("Display name recorded on the ability set."));
			Schema.String(TEXT("setPath"), TEXT("Canonical /Game ability set asset path."));
			Schema.StringEnum(TEXT("setting"), { TEXT("add_attribute"), TEXT("base_value"), TEXT("clamping"), TEXT("configure"), TEXT("add_component"), TEXT("duration"), TEXT("stacking"), TEXT("tags"), TEXT("add_modifier"), TEXT("modifier_magnitude"), TEXT("add_execution_calculation"), TEXT("add_cue"), TEXT("cooldown"), TEXT("costs"), TEXT("targeting"), TEXT("activation_policy"), TEXT("instancing_policy"), TEXT("add_task"), TEXT("add_to_set"), TEXT("grant"), TEXT("trigger"), TEXT("effects") }, TEXT("Which configure ability variant to run."));
			Schema.String(TEXT("soundPath"), TEXT("Canonical /Game sound asset path."));
			Schema.StringEnum(TEXT("stackDurationRefreshPolicy"), { TEXT("RefreshOnSuccessfulApplication"), TEXT("NeverRefresh") }, TEXT("When stack duration refreshes."));
			Schema.StringEnum(TEXT("stackExpirationPolicy"), { TEXT("ClearEntireStack"), TEXT("RemoveSingleStackAndRefreshDuration"), TEXT("RefreshDuration") }, TEXT("What happens when a stack expires."));
			Schema.Number(TEXT("stackLimitCount"), TEXT("Maximum stack count."));
			Schema.StringEnum(TEXT("stackPeriodResetPolicy"), { TEXT("ResetOnSuccessfulApplication"), TEXT("NeverReset") }, TEXT("When the stack period resets."));
			Schema.StringEnum(TEXT("stackingType"), { TEXT("None"), TEXT("AggregateBySource"), TEXT("AggregateByTarget") }, TEXT("Stacking aggregation for the effect."));
			Schema.String(TEXT("tag"), TEXT("Gameplay tag string."));
			Schema.String(TEXT("tagName"), TEXT("String parameter."));
			Schema.String(TEXT("targetAttribute"), TEXT("Target attribute captured by the modifier."));
			Schema.Number(TEXT("targetRange"), TEXT("Maximum targeting range in world units."));
			Schema.StringEnum(TEXT("targetingMode"), { TEXT("None"), TEXT("SingleTarget"), TEXT("AOE"), TEXT("Directional"), TEXT("Ground"), TEXT("ActorPlacement") }, TEXT("Targeting mode for the ability."));
			Schema.String(TEXT("taskType"), TEXT("String parameter."));
			Schema.StringEnum(TEXT("triggerType"), { TEXT("OnActive"), TEXT("WhileActive"), TEXT("Executed"), TEXT("OnRemove") }, TEXT("When the gameplay cue triggers."));
			Schema.StringEnum(TEXT("action"), { TEXT("configure_asc"), TEXT("create_gas_asset"), TEXT("configure_attribute_set"), TEXT("configure_ability"), TEXT("configure_gameplay_effect"), TEXT("configure_gameplay_cue"), TEXT("add_tag_to_asset"), TEXT("get_gas_info") }, TEXT("Action to invoke on manage_gas."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};

class FMcpGenTool_ManageInventory : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_inventory"); }
	FString GetDescription() const override { return TEXT("Create item data assets, inventory components, world pickups, loot tables, and crafting recipes."); }
	FString GetCategory() const override { return TEXT("gameplay"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.Bool(TEXT("abilityGrants"), TEXT("Whether equipment grants abilities."));
			Schema.String(TEXT("actorPath"), TEXT("Canonical /Game actor Blueprint asset path that drops loot."));
			Schema.Bool(TEXT("attachToSocket"), TEXT("Whether equipped items attach to a socket."));
			Schema.String(TEXT("blueprintPath"), TEXT("Canonical /Game Blueprint asset path."));
			Schema.Bool(TEXT("bobbing"), TEXT("Whether the pickup bobs vertically."));
			Schema.String(TEXT("categoryPath"), TEXT("Canonical /Game item category asset path."));
			Schema.String(TEXT("componentName"), TEXT("Name for the component added to the Blueprint."));
			Schema.Number(TEXT("craftTime"), TEXT("Craft duration in seconds."));
			Schema.Number(TEXT("craftingSpeedMultiplier"), TEXT("Crafting speed multiplier applied by the station."));
			Schema.String(TEXT("defaultSocket"), TEXT("Default attachment socket name for equipped items."));
			Schema.Number(TEXT("dropCount"), TEXT("Number of loot stacks dropped."));
			Schema.Bool(TEXT("dropOnDeath"), TEXT("Whether loot drops when the actor dies."));
			Schema.Number(TEXT("dropRadius"), TEXT("Loot scatter radius in world units."));
			Schema.Bool(TEXT("enableWeight"), TEXT("Whether the carry-weight system is enabled."));
			Schema.Bool(TEXT("encumberanceSystem"), TEXT("Whether the encumberance system is enabled."));
			Schema.Number(TEXT("encumberanceThreshold"), TEXT("Encumberance threshold as a fraction of max weight."));
			Schema.Number(TEXT("entryIndex"), TEXT("Zero-based loot entry index to remove."));
			Schema.Bool(TEXT("glowEffect"), TEXT("Whether the pickup emits a glow effect."));
			Schema.String(TEXT("iconPath"), TEXT("Canonical /Game texture or material path used as the item icon."));
			Schema.String(TEXT("ingredientItemPath"), TEXT("Canonical /Game ingredient item asset path."));
			Schema.String(TEXT("interactionType"), TEXT("Pickup interaction type (Overlap, Interact, or Key)."));
			Schema.String(TEXT("itemPath"), TEXT("Canonical /Game item definition asset path."));
			Schema.StringEnum(TEXT("kind"), { TEXT("item_data_asset"), TEXT("item_category"), TEXT("loot_table"), TEXT("crafting_recipe"), TEXT("crafting_station"), TEXT("pickup_actor") }, TEXT("Which create inventory asset variant to run."));
			Schema.String(TEXT("lootTablePath"), TEXT("Canonical /Game loot table asset path."));
			Schema.Number(TEXT("lootWeight"), TEXT("Relative selection weight for the loot entry."));
			Schema.Number(TEXT("maxQuantity"), TEXT("Maximum quantity granted by the loot entry."));
			Schema.Number(TEXT("maxStackSize"), TEXT("Maximum stack size."));
			Schema.Number(TEXT("maxWeight"), TEXT("Maximum carry weight."));
			Schema.Number(TEXT("minQuantity"), TEXT("Minimum quantity granted by the loot entry."));
			Schema.String(TEXT("name"), TEXT("Name for the created asset or actor."));
			Schema.String(TEXT("outputItemPath"), TEXT("Canonical /Game item asset path produced by the recipe."));
			Schema.Number(TEXT("outputQuantity"), TEXT("Quantity produced per craft."));
			Schema.Bool(TEXT("passiveEffects"), TEXT("Whether equipment applies passive effects."));
			Schema.String(TEXT("path"), TEXT("Canonical /Game output path for the created asset."));
			Schema.String(TEXT("pickupPath"), TEXT("Canonical /Game pickup Blueprint asset path."));
			Schema.String(TEXT("prompt"), TEXT("Pickup interaction prompt text."));
			Schema.FreeformObject(TEXT("properties"), TEXT("Key-value property map."));
			Schema.Number(TEXT("quantity"), TEXT("Ingredient quantity consumed per craft."));
			Schema.String(TEXT("recipePath"), TEXT("Canonical /Game crafting recipe asset path."));
			Schema.Array(TEXT("recipePaths"), TEXT("List of string values."), TEXT("string"));
			Schema.Bool(TEXT("replicated"), TEXT("Whether the inventory component replicates."));
			Schema.String(TEXT("replicationCondition"), TEXT("Replication condition name applied to inventory state."));
			Schema.Number(TEXT("requiredLevel"), TEXT("Minimum character level required to craft."));
			Schema.String(TEXT("requiredStation"), TEXT("Crafting station type required by the recipe."));
			Schema.Number(TEXT("respawnTime"), TEXT("Pickup respawn delay in seconds."));
			Schema.Bool(TEXT("respawnable"), TEXT("Whether the pickup respawns after collection."));
			Schema.Bool(TEXT("rotation"), TEXT("Whether the pickup spins in place."));
			Schema.Bool(TEXT("save"), TEXT("Persist the created/modified asset to disk."));
			Schema.StringEnum(TEXT("setting"), { TEXT("add_component"), TEXT("add_recipe_ingredient"), TEXT("recipe_requirements"), TEXT("station_recipes"), TEXT("add_entry"), TEXT("remove_entry"), TEXT("quality_tiers"), TEXT("drop"), TEXT("create_component"), TEXT("add_functions"), TEXT("define_slots"), TEXT("visuals"), TEXT("effects"), TEXT("slots"), TEXT("weight"), TEXT("events"), TEXT("replication"), TEXT("interaction"), TEXT("respawn"), TEXT("properties"), TEXT("icon"), TEXT("stacking"), TEXT("category") }, TEXT("Which configure crafting variant to run."));
			Schema.Number(TEXT("slotCount"), TEXT("Number of inventory slots to author."));
			Schema.Array(TEXT("slots"), TEXT("List of string values."), TEXT("string"));
			Schema.Bool(TEXT("stackable"), TEXT("Whether the item stacks."));
			Schema.Bool(TEXT("statModifiers"), TEXT("Whether equipment grants stat modifiers."));
			Schema.String(TEXT("stationPath"), TEXT("Canonical /Game crafting station Blueprint asset path."));
			Schema.String(TEXT("stationType"), TEXT("Crafting station type."));
			Schema.ArrayOfObjects(TEXT("tiers"), TEXT("Quality tiers, each with a name and a dropWeight."), [](FMcpSchemaBuilder& S) {
				  S.String(TEXT("name"), TEXT("Quality tier name."));
				  S.Number(TEXT("dropWeight"), TEXT("Relative drop weight for the tier."));
				  S.Required({ TEXT("name"), TEXT("dropWeight") });
			});
			Schema.Bool(TEXT("uniqueItems"), TEXT("Whether duplicate instances of the item are disallowed."));
			Schema.StringEnum(TEXT("action"), { TEXT("configure_crafting"), TEXT("configure_equipment"), TEXT("configure_inventory"), TEXT("configure_loot"), TEXT("configure_item"), TEXT("configure_pickup"), TEXT("create_inventory_asset"), TEXT("get_inventory_info") }, TEXT("Action to invoke on manage_inventory."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedGameplay_SysCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ManageGas());

	Registry.Register(new FMcpGenTool_ManageInventory());

}
