// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_ManageAi : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_ai"); }
	FString GetDescription() const override { return TEXT("Build AI systems: AI controllers, Behavior Trees, Blackboards, EQS, perception, State Trees, Smart Objects, NavMesh settings, nav modifiers, links, and pathfinding."); }
	FString GetCategory() const override { return TEXT("gameplay"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("actorName"), TEXT("Target actor name in the current level."));
			Schema.Number(TEXT("agentHeight"), TEXT("Navigation agent height (default: 144)."));
			Schema.Number(TEXT("agentMaxSlope"), TEXT("Maximum slope angle in degrees (default: 44)."));
			Schema.Number(TEXT("agentRadius"), TEXT("Navigation agent radius (default: 35)."));
			Schema.Number(TEXT("agentStepHeight"), TEXT("Maximum step height the agent can climb (default: 35)."));
			Schema.String(TEXT("areaClass"), TEXT("Navigation area class path."));
			Schema.Number(TEXT("areaCost"), TEXT("Pathfinding cost multiplier for the area (1.0 = normal)."));
			Schema.String(TEXT("assetPath"), TEXT("Canonical /Game asset path."));
			Schema.Bool(TEXT("bCreateBoxObstacle"), TEXT("Add a box obstacle during navigation generation."));
			Schema.String(TEXT("baseObjectClass"), TEXT("Base class filter for Object/Class blackboard keys."));
			Schema.String(TEXT("behaviorTreePath"), TEXT("Canonical /Game Behavior Tree asset path."));
			Schema.String(TEXT("blackboardPath"), TEXT("Canonical /Game Blackboard asset path."));
			Schema.String(TEXT("blueprintPath"), TEXT("Canonical /Game Blueprint asset path."));
			Schema.Number(TEXT("brakingDeceleration"), TEXT("Braking deceleration while walking; left unchanged when omitted."));
			Schema.Number(TEXT("broadcastInterval"), TEXT("Interval for the state-change broadcast (0 = single)."));
			Schema.Number(TEXT("broadcastRadius"), TEXT("Radius for the state-change broadcast."));
			Schema.Number(TEXT("cellHeight"), TEXT("NavMesh cell height (default: 10)."));
			Schema.Number(TEXT("cellSize"), TEXT("NavMesh cell size (default: 19)."));
			Schema.String(TEXT("childNodeId"), TEXT("ID of the child node."));
			Schema.String(TEXT("comment"), TEXT("Comment text applied to the graph node."));
			Schema.String(TEXT("componentName"), TEXT("Name of the component to add."));
			Schema.StringEnum(TEXT("compositeType"), { TEXT("Selector"), TEXT("Sequence"), TEXT("Parallel"), TEXT("SimpleParallel") }, TEXT("Composite node type."));
			Schema.String(TEXT("configPath"), TEXT("Canonical /Game Mass Entity config asset path."));
			Schema.StringEnum(TEXT("contextType"), { TEXT("Querier"), TEXT("Item"), TEXT("EnvQueryContext_BlueprintBase"), TEXT("Custom") }, TEXT("EQS context type."));
			Schema.StringEnum(TEXT("control"), { TEXT("run"), TEXT("stop"), TEXT("assign_tree"), TEXT("assign_blackboard") }, TEXT("Which run behavior tree variant to run; omit for 'run'."));
			Schema.String(TEXT("controllerPath"), TEXT("Canonical /Game AI controller asset path."));
			Schema.Object(TEXT("damageConfig"), TEXT("AI damage sense configuration."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("maxAge"), TEXT(""));
			});
			Schema.StringEnum(TEXT("decoratorType"), { TEXT("Blackboard"), TEXT("BlackboardBased"), TEXT("CompareBBEntries"), TEXT("Cooldown"), TEXT("ConeCheck"), TEXT("DoesPathExist"), TEXT("IsAtLocation"), TEXT("IsBBEntryOfClass"), TEXT("KeepInCone"), TEXT("Loop"), TEXT("SetTagCooldown"), TEXT("TagCooldown"), TEXT("TimeLimit"), TEXT("ForceSuccess"), TEXT("ConditionalLoop"), TEXT("Custom") }, TEXT("Decorator node type."));
			Schema.String(TEXT("definitionPath"), TEXT("Canonical /Game Smart Object definition asset path."));
			Schema.StringEnum(TEXT("direction"), { TEXT("BothWays"), TEXT("LeftToRight"), TEXT("RightToLeft") }, TEXT("Link traversal direction."));
			Schema.String(TEXT("disabledAreaClass"), TEXT("Area class applied while the smart link is disabled."));
			Schema.StringEnum(TEXT("dominantSense"), { TEXT("Sight"), TEXT("Hearing"), TEXT("Damage"), TEXT("Touch"), TEXT("None") }, TEXT("Dominant sense for perception prioritization."));
			Schema.StringEnum(TEXT("edit"), { TEXT("add_composite"), TEXT("add_task"), TEXT("add_decorator"), TEXT("add_service"), TEXT("add_node"), TEXT("add_subnode"), TEXT("connect"), TEXT("break_connections"), TEXT("configure_node"), TEXT("set_node_properties"), TEXT("remove_node"), TEXT("add_key"), TEXT("set_value"), TEXT("set_key_instance_synced"), TEXT("create_config"), TEXT("configure"), TEXT("add_spawner"), TEXT("create_definition"), TEXT("add_slot"), TEXT("configure_slot"), TEXT("add_component"), TEXT("create"), TEXT("add_generator"), TEXT("add_test"), TEXT("add_context"), TEXT("configure_test_scoring"), TEXT("add_state"), TEXT("add_transition"), TEXT("configure_task") }, TEXT("Which edit behavior tree variant to run."));
			Schema.Bool(TEXT("enableDamage"), TEXT("Enable the damage sense."));
			Schema.Bool(TEXT("enableHearing"), TEXT("Enable the hearing sense."));
			Schema.Bool(TEXT("enableSight"), TEXT("Enable the sight sense."));
			Schema.Bool(TEXT("enabled"), TEXT("Whether the slot is enabled."));
			Schema.String(TEXT("enabledAreaClass"), TEXT("Area class applied while the smart link is enabled."));
			Schema.Object(TEXT("endPoint"), TEXT("End point of the navigation link (relative to the actor)."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT(""));
				  S.Number(TEXT("y"), TEXT(""));
				  S.Number(TEXT("z"), TEXT(""));
			});
			Schema.Object(TEXT("failsafeExtent"), TEXT("Failsafe extent used when the actor has no collision."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT(""));
				  S.Number(TEXT("y"), TEXT(""));
				  S.Number(TEXT("z"), TEXT(""));
			});
			Schema.Bool(TEXT("failsafeToDefaultNavmesh"), TEXT("Fall back to the default navmesh area when the modifier area class is unset."));
			Schema.String(TEXT("focusActorName"), TEXT("Actor the controller should focus on."));
			Schema.StringEnum(TEXT("focusOp"), { TEXT("set"), TEXT("clear") }, TEXT("Which set focus variant to run; omit for 'set'."));
			Schema.String(TEXT("fromState"), TEXT("Source state name."));
			Schema.Object(TEXT("generatorSettings"), TEXT("Generator-specific settings."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("searchRadius"), TEXT(""));
				  S.String(TEXT("searchCenter"), TEXT(""));
				  S.String(TEXT("actorClass"), TEXT(""));
				  S.Number(TEXT("gridSize"), TEXT(""));
				  S.Number(TEXT("spacesBetween"), TEXT(""));
				  S.Number(TEXT("innerRadius"), TEXT(""));
				  S.Number(TEXT("outerRadius"), TEXT(""));
			});
			Schema.StringEnum(TEXT("generatorType"), { TEXT("ActorsOfClass"), TEXT("CurrentLocation"), TEXT("Donut"), TEXT("OnCircle"), TEXT("PathingGrid"), TEXT("SimpleGrid"), TEXT("Composite"), TEXT("Custom") }, TEXT("EQS generator type."));
			Schema.Object(TEXT("hearingConfig"), TEXT("AI hearing sense configuration."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("hearingRange"), TEXT(""));
				  S.Number(TEXT("loSHearingRange"), TEXT(""));
				  S.Bool(TEXT("detectFriendly"), TEXT(""));
				  S.Number(TEXT("maxAge"), TEXT(""));
			});
			Schema.Number(TEXT("hearingRange"), TEXT("Hearing range in world units."));
			Schema.StringEnum(TEXT("info"), { TEXT("ai"), TEXT("navigation"), TEXT("tree"), TEXT("blackboard_value") }, TEXT("Which get ai info variant to run; omit for 'ai'."));
			Schema.Bool(TEXT("isInstanceSynced"), TEXT("Sync key across instances."));
			Schema.String(TEXT("keyName"), TEXT("Blackboard key name."));
			Schema.StringEnum(TEXT("keyType"), { TEXT("Bool"), TEXT("Int"), TEXT("Float"), TEXT("Vector"), TEXT("Rotator"), TEXT("Object"), TEXT("Class"), TEXT("Enum"), TEXT("Name"), TEXT("String") }, TEXT("Blackboard key data type."));
			Schema.StringEnum(TEXT("kind"), { TEXT("behavior_tree"), TEXT("graph_route"), TEXT("blackboard"), TEXT("link_proxy"), TEXT("smart_link"), TEXT("modifier"), TEXT("modifier_component") }, TEXT("Which create behavior tree variant to run; omit for 'behavior_tree'."));
			Schema.Bool(TEXT("linkEnabled"), TEXT("Whether the link is enabled."));
			Schema.StringEnum(TEXT("linkType"), { TEXT("simple"), TEXT("smart") }, TEXT("Type of navigation link."));
			Schema.Object(TEXT("location"), TEXT("World location for the spawned link actor."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT(""));
				  S.Number(TEXT("y"), TEXT(""));
				  S.Number(TEXT("z"), TEXT(""));
			});
			Schema.Number(TEXT("loseSightRadius"), TEXT("Radius at which sight is lost."));
			Schema.Number(TEXT("maxAcceleration"), TEXT("Maximum acceleration; left unchanged when omitted."));
			Schema.Number(TEXT("maxSimplificationError"), TEXT("Edge simplification error."));
			Schema.Number(TEXT("maxWalkSpeed"), TEXT("Maximum ground speed; left unchanged when omitted."));
			Schema.Number(TEXT("mergeRegionSize"), TEXT("Region merge threshold."));
			Schema.Number(TEXT("minRegionArea"), TEXT("Minimum region area to keep."));
			Schema.String(TEXT("name"), TEXT("Name for the created asset or actor."));
			Schema.String(TEXT("nodeClass"), TEXT("Node class path."));
			Schema.String(TEXT("nodeId"), TEXT("ID of the node."));
			Schema.String(TEXT("nodeName"), TEXT("Name for the created composite node."));
			Schema.String(TEXT("nodeType"), TEXT("Behavior Tree graph node type."));
			Schema.String(TEXT("obstacleAreaClass"), TEXT("Area class for the box obstacle."));
			Schema.Object(TEXT("obstacleExtent"), TEXT("Extent of the simple box obstacle."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT(""));
				  S.Number(TEXT("y"), TEXT(""));
				  S.Number(TEXT("z"), TEXT(""));
			});
			Schema.Object(TEXT("obstacleOffset"), TEXT("Offset of the simple box obstacle."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT(""));
				  S.Number(TEXT("y"), TEXT(""));
				  S.Number(TEXT("z"), TEXT(""));
			});
			Schema.Object(TEXT("offset"), TEXT("Slot offset relative to the definition origin."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT(""));
				  S.Number(TEXT("y"), TEXT(""));
				  S.Number(TEXT("z"), TEXT(""));
			});
			Schema.String(TEXT("parentConfigPath"), TEXT("Parent Mass entity config asset to inherit from."));
			Schema.String(TEXT("parentNodeId"), TEXT("ID of the parent node: 'root', a node GUID, or a node id as returned by add_composite/add_task (for example BTComposite_Selector_0)."));
			Schema.String(TEXT("parentStateName"), TEXT("Parent state name for the added state."));
			Schema.String(TEXT("path"), TEXT("Canonical /Game output path for the created asset."));
			Schema.Number(TEXT("peripheralVisionAngle"), TEXT("Peripheral vision half-angle in degrees."));
			Schema.AnyValue(TEXT("properties"), TEXT("Key-value property map."));
			Schema.String(TEXT("queryPath"), TEXT("Canonical /Game Environment Query asset path."));
			Schema.Object(TEXT("rotation"), TEXT("Rotation as {pitch, yaw, roll} in degrees."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("pitch"), TEXT(""));
				  S.Number(TEXT("yaw"), TEXT(""));
				  S.Number(TEXT("roll"), TEXT(""));
			});
			Schema.Number(TEXT("rotationRate"), TEXT("Yaw rotation rate in degrees per second; left unchanged when omitted."));
			Schema.Bool(TEXT("save"), TEXT("Persist the created/modified asset to disk."));
			Schema.String(TEXT("savePath"), TEXT("Directory path used when saving the created Behavior Tree."));
			Schema.String(TEXT("selectionBehavior"), TEXT("State selection behavior (e.g. TryEnterState, TrySelectChildrenInOrder, TryFollowTransitions)."));
			Schema.StringEnum(TEXT("serviceType"), { TEXT("DefaultFocus"), TEXT("RunEQS"), TEXT("Custom") }, TEXT("Service node type."));
			Schema.StringEnum(TEXT("setting"), { TEXT("mesh_settings"), TEXT("agent_properties"), TEXT("area_cost"), TEXT("area_class"), TEXT("nav_link"), TEXT("link_type"), TEXT("smart_link_behavior"), TEXT("rebuild"), TEXT("setup"), TEXT("add_component"), TEXT("sight"), TEXT("hearing"), TEXT("damage"), TEXT("team"), TEXT("controller") }, TEXT("Which configure navigation variant to run."));
			Schema.Object(TEXT("sightConfig"), TEXT("AI sight sense configuration."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("sightRadius"), TEXT(""));
				  S.Number(TEXT("loseSightRadius"), TEXT(""));
				  S.Number(TEXT("peripheralVisionAngle"), TEXT(""));
				  S.Number(TEXT("pointOfViewBackwardOffset"), TEXT(""));
				  S.Number(TEXT("nearClippingRadius"), TEXT(""));
				  S.Number(TEXT("autoSuccessRange"), TEXT(""));
				  S.Number(TEXT("maxAge"), TEXT(""));
				  S.Object(TEXT("detectionByAffiliation"), TEXT("Affiliation detection flags."), [](FMcpSchemaBuilder& S) {
				  	  S.Bool(TEXT("enemies"), TEXT(""));
				  	  S.Bool(TEXT("neutrals"), TEXT(""));
				  	  S.Bool(TEXT("friendlies"), TEXT(""));
				  });
			});
			Schema.Number(TEXT("sightRadius"), TEXT("Sight radius in world units."));
			Schema.Number(TEXT("slotIndex"), TEXT("Index of the slot to configure."));
			Schema.Number(TEXT("snapRadius"), TEXT("Snap radius for link endpoints (default: 30)."));
			Schema.Number(TEXT("spawnCount"), TEXT("Number of entities the spawner creates."));
			Schema.Object(TEXT("startPoint"), TEXT("Start point of the navigation link (relative to the actor)."), [](FMcpSchemaBuilder& S) {
				  S.Number(TEXT("x"), TEXT(""));
				  S.Number(TEXT("y"), TEXT(""));
				  S.Number(TEXT("z"), TEXT(""));
			});
			Schema.String(TEXT("stateName"), TEXT("State name."));
			Schema.String(TEXT("stateTreePath"), TEXT("Canonical /Game State Tree asset path."));
			Schema.String(TEXT("stateType"), TEXT("State kind for the added state."));
			Schema.StringEnum(TEXT("subnodeType"), { TEXT("Decorator"), TEXT("Service") }, TEXT("Behavior Tree subnode kind for add_subnode."));
			Schema.Number(TEXT("taskIndex"), TEXT("Zero-based task index in the state (alternative to taskName)."));
			Schema.String(TEXT("taskName"), TEXT("Task to configure, matched by class or instance name (defaults to the first task)."));
			Schema.StringEnum(TEXT("taskType"), { TEXT("MoveTo"), TEXT("MoveDirectlyToward"), TEXT("RotateToFaceBBEntry"), TEXT("Wait"), TEXT("WaitBlackboardTime"), TEXT("PlayAnimation"), TEXT("PlaySound"), TEXT("RunEQSQuery"), TEXT("RunBehaviorDynamic"), TEXT("SetBlackboardValue"), TEXT("PushPawnAction"), TEXT("FinishWithResult"), TEXT("MakeNoise"), TEXT("GameplayTaskBase"), TEXT("Custom") }, TEXT("Task node type."));
			Schema.Number(TEXT("teamId"), TEXT("Team ID for perception affiliation (0=Neutral, 1=Player, 2=Enemy, ...)."));
			Schema.Number(TEXT("testIndex"), TEXT("Index of the test to configure."));
			Schema.Object(TEXT("testSettings"), TEXT("Test scoring and filter settings."), [](FMcpSchemaBuilder& S) {
				  S.StringEnum(TEXT("scoringEquation"), { TEXT("Linear"), TEXT("Square"), TEXT("InverseLinear"), TEXT("Constant") }, TEXT(""));
				  S.Number(TEXT("clampMin"), TEXT(""));
				  S.Number(TEXT("clampMax"), TEXT(""));
				  S.StringEnum(TEXT("filterType"), { TEXT("Minimum"), TEXT("Maximum"), TEXT("Range") }, TEXT(""));
				  S.Number(TEXT("floatMin"), TEXT(""));
				  S.Number(TEXT("floatMax"), TEXT(""));
			});
			Schema.StringEnum(TEXT("testType"), { TEXT("Distance"), TEXT("Dot"), TEXT("GameplayTags"), TEXT("Overlap"), TEXT("Pathfinding"), TEXT("PathfindingBatch"), TEXT("Project"), TEXT("Random"), TEXT("Trace"), TEXT("Custom") }, TEXT("EQS test type."));
			Schema.Number(TEXT("tileSizeUU"), TEXT("NavMesh tile size in Unreal units (default: 1000)."));
			Schema.String(TEXT("toState"), TEXT("Target state name."));
			Schema.String(TEXT("traitClass"), TEXT("Trait class name whose properties are configured."));
			Schema.Number(TEXT("traitIndex"), TEXT("Zero-based trait index (alternative to traitClass)."));
			Schema.String(TEXT("triggerType"), TEXT("Transition trigger kind."));
			Schema.AnyValue(TEXT("value"), TEXT("Property value (any type)."));
			Schema.Number(TEXT("x"), TEXT("Graph node X coordinate."));
			Schema.Number(TEXT("y"), TEXT("Graph node Y coordinate."));
			Schema.StringEnum(TEXT("action"), { TEXT("setup_perception"), TEXT("edit_blackboard"), TEXT("edit_behavior_tree"), TEXT("edit_eqs_query"), TEXT("edit_mass_entity"), TEXT("edit_smart_object"), TEXT("edit_state_tree"), TEXT("run_behavior_tree"), TEXT("set_focus"), TEXT("configure_navigation"), TEXT("create_behavior_tree"), TEXT("create_ai_controller"), TEXT("create_nav_actor"), TEXT("get_ai_info"), TEXT("get_tree"), TEXT("set_ai_movement") }, TEXT("Action to invoke on manage_ai."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};

class FMcpGenTool_ManageInteraction : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_interaction"); }
	FString GetDescription() const override { return TEXT("Create interactive objects: doors, switches, chests, levers. Set up destructible meshes and trigger volumes."); }
	FString GetCategory() const override { return TEXT("gameplay"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("actorName"), TEXT("Target actor name in the current level."));
			Schema.Bool(TEXT("autoClose"), TEXT("Whether the door closes automatically."));
			Schema.Number(TEXT("autoCloseDelay"), TEXT("Delay in seconds before the door auto-closes."));
			Schema.String(TEXT("blueprintPath"), TEXT("Canonical /Game Blueprint asset path."));
			Schema.Bool(TEXT("canToggle"), TEXT("Whether the switch can toggle back off."));
			Schema.String(TEXT("chestPath"), TEXT("Canonical /Game chest actor Blueprint asset path."));
			Schema.String(TEXT("componentName"), TEXT("Name for the component added to the Blueprint."));
			Schema.String(TEXT("doorPath"), TEXT("Canonical /Game door actor Blueprint asset path."));
			Schema.String(TEXT("folder"), TEXT("Canonical /Game folder that receives the created asset."));
			Schema.StringEnum(TEXT("kind"), { TEXT("door"), TEXT("chest"), TEXT("switch"), TEXT("lever"), TEXT("trigger"), TEXT("interface"), TEXT("component") }, TEXT("Which create interactable variant to run."));
			Schema.Bool(TEXT("locked"), TEXT("Whether the interactable starts locked."));
			Schema.String(TEXT("lootTablePath"), TEXT("Canonical /Game loot table asset path."));
			Schema.String(TEXT("name"), TEXT("Name for the created asset or actor."));
			Schema.Number(TEXT("openAngle"), TEXT("Open angle in degrees."));
			Schema.Number(TEXT("openTime"), TEXT("Open animation duration in seconds."));
			Schema.String(TEXT("promptTextFormat"), TEXT("Interaction prompt format string, e.g. \"Press {Key} to Interact\"."));
			Schema.Bool(TEXT("requiresKey"), TEXT("Whether opening requires a key."));
			Schema.Number(TEXT("resetTime"), TEXT("Switch reset delay in seconds."));
			Schema.StringEnum(TEXT("setting"), { TEXT("add_component"), TEXT("setup_mesh"), TEXT("damage"), TEXT("effects"), TEXT("levels"), TEXT("door"), TEXT("chest"), TEXT("switch"), TEXT("trigger_events"), TEXT("trigger_filter"), TEXT("trigger_response"), TEXT("trace"), TEXT("widget"), TEXT("add_events") }, TEXT("Which configure destruction variant to run."));
			Schema.Bool(TEXT("showOnHover"), TEXT("Whether the interaction widget appears on hover."));
			Schema.Bool(TEXT("showPromptText"), TEXT("Whether the interaction widget shows prompt text."));
			Schema.String(TEXT("switchPath"), TEXT("Canonical /Game switch actor Blueprint asset path."));
			Schema.String(TEXT("switchType"), TEXT("Switch type (button, lever, or pressure_plate)."));
			Schema.Number(TEXT("traceDistance"), TEXT("Interaction trace distance in world units."));
			Schema.Number(TEXT("traceRadius"), TEXT("Interaction trace radius in world units."));
			Schema.String(TEXT("traceType"), TEXT("Interaction trace shape (line, sphere, or box)."));
			Schema.String(TEXT("triggerPath"), TEXT("Canonical /Game trigger actor Blueprint asset path."));
			Schema.String(TEXT("triggerShape"), TEXT("Trigger volume shape (box, sphere, or capsule)."));
			Schema.String(TEXT("widgetClass"), TEXT("Canonical /Game interaction widget class path."));
			Schema.StringEnum(TEXT("action"), { TEXT("configure_destruction"), TEXT("configure_interactable"), TEXT("create_interactable"), TEXT("get_interaction_info") }, TEXT("Action to invoke on manage_interaction."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedGameplay_AICapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_ManageAi());

	Registry.Register(new FMcpGenTool_ManageInteraction());

}
