// GENERATED by scripts/generate-console-command-policy.ts -- do not edit.
// One canonical console-command policy shared by the native validator.
// Source of truth: scripts/generate-console-command-policy.ts ->
//   src/utils/commands/console-command-policy-rules.ts (Task 6 typed data).
// GENERATED artifacts are never hand-edited; re-run the generator after a rule change.
#pragma once
#include "CoreMinimal.h"

namespace McpGeneratedConsoleCommandPolicy
{
    // Unsafe separators checked on both surfaces.
    static const TCHAR* const UNSAFE_SEPARATORS[] = {
        TEXT("\n"),
        TEXT("\r"),
        TEXT("&&"),
        TEXT("||"),
        TEXT(";"),
        TEXT("|"),
        TEXT("`"),
    };

    // Commands blocked for security (DANGEROUS/RESTRICTED engine commands, py/python).
    static const TCHAR* const BLOCKED_COMMANDS[] = {
        TEXT("shutdown"),
        TEXT("quit"),
        TEXT("exit"),
        TEXT("kill"),
        TEXT("crash"),
        TEXT("r.gpucrash"),
        TEXT("r.crash"),
        TEXT("forcecrash"),
        TEXT("debugbreak"),
        TEXT("buildpaths"),
        TEXT("rebuildnavigation"),
        TEXT("recompileglobalshaders"),
        TEXT("deriveddatacache"),
        TEXT("py"),
        TEXT("python"),
    };

    static const TCHAR* const RESTRICTED_COMMANDS[] = {
        TEXT("delete"),
        TEXT("destroy"),
        TEXT("unrealbuildtool"),
        TEXT("ubt"),
        TEXT("mcp.fab.addtoproject"),
        TEXT("mcp.fab.describecatalogshape"),
    };

    static const TCHAR* const FORBIDDEN_COMMAND_NAMES[] = {
        TEXT("rm"),
        TEXT("del"),
        TEXT("format"),
        TEXT("copy"),
        TEXT("move"),
        TEXT("start"),
    };

    static const TCHAR* const FORBIDDEN_TOKENS[] = {
        TEXT("import os"),
        TEXT("import sys"),
        TEXT("import subprocess"),
        TEXT("subprocess."),
        TEXT("os.system"),
        TEXT("exec("),
        TEXT("eval("),
        TEXT("__import__"),
        TEXT("with open"),
        TEXT("open("),
        TEXT("write("),
        TEXT("read("),
        TEXT("debug crash"),
        TEXT("debug break"),
        TEXT("assert false"),
        TEXT("check(false)"),
        TEXT("viewmode visualizebuffer basecolor"),
        TEXT("viewmode visualizebuffer worldnormal"),
        TEXT("obj garbage"),
        TEXT("obj list"),
        TEXT("memreport"),
    };
}
