// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyTypeSystem.h"
#include "Eclipse_9000TypeSystem.generated.h"

/** Articy Type System */
UCLASS(BlueprintType)
class ECLIPSE_API UEclipse_9000TypeSystem : public UArticyTypeSystem
{
	GENERATED_BODY()
	
};
