// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyDatabase.h"
#include "Eclipse_9000ExpressoScripts.h"
#include "Eclipse_9000Database.generated.h"

UCLASS(BlueprintType)
class ECLIPSE_API UEclipse_9000Database : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	
	/** Get the instance (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static UEclipse_9000Database* Get(const UObject* WorldContext) 
	{
		return static_cast<UEclipse_9000Database*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UEclipse_9000GlobalVariables* GetGVs() const override
	{
		return static_cast<UEclipse_9000GlobalVariables*>(Super::GetGVs());
	}
	/** Gets the current runtime instance of a set of GVs. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UEclipse_9000GlobalVariables* GetRuntimeGVs(UArticyAlternativeGlobalVariables* Asset) const override
	{
		return static_cast<UEclipse_9000GlobalVariables*>(Super::GetRuntimeGVs(Asset));
	}
};
