// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "Eclipse_9000Interfaces.generated.h"


/** UNINTERFACE generated from Articy Basic Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Eclipse_9000 Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UEclipse_9000ObjectWithDefaultBasicCharacterFeature : public UInterface { GENERATED_BODY() };
class IEclipse_9000ObjectWithDefaultBasicCharacterFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UEclipse_9000DefaultBasicCharacterFeature* GetFeatureDefaultBasicCharacterFeature() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy Extended Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Eclipse_9000 Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UEclipse_9000ObjectWithDefaultExtendedCharacterFeature : public UInterface { GENERATED_BODY() };
class IEclipse_9000ObjectWithDefaultExtendedCharacterFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UEclipse_9000DefaultExtendedCharacterFeature* GetFeatureDefaultExtendedCharacterFeature() const
	{
		return nullptr;
	}
};
