// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyExpressoScripts.h"
#include "Eclipse_9000GlobalVariables.h"
#include "Eclipse_9000ExpressoScripts.generated.h"

UINTERFACE(Blueprintable)
class UEclipse_9000MethodsProvider : public UInterface { GENERATED_BODY() };
class IEclipse_9000MethodsProvider
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category="Articy Methods Provider", meta=(DisplayName="talkedTo"))
	bool talkedTo_Int(int aParam0) ;
	virtual bool talkedTo_Int_Implementation(int aParam0) { return true; };
};

UCLASS(BlueprintType, Blueprintable)
class ECLIPSE_API UEclipse_9000ExpressoScripts : public UArticyExpressoScripts
{
	GENERATED_BODY()
	
private:
	
	bool talkedTo(int aParam0) const
	{
		auto methodProvider = GetUserMethodsProviderObject();
		if(!methodProvider) return true;
		return IEclipse_9000MethodsProvider::Execute_talkedTo_Int(methodProvider, aParam0);
	}
	
private:
	
	mutable TWeakObjectPtr<UEclipse_9000GlobalVariables> ActiveGlobals = nullptr;
	
	/** Auto-emitted fallbacks for identifiers referenced in script */
	/** fragments but not yet declared as Global Variables in Articy. */
	/** Default false; add the real GVar to Articy and re-export to replace. */
	mutable bool an = false;
	mutable bool Angel = false;
	mutable bool be = false;
	mutable bool empty = false;
	mutable bool Eye = false;
	mutable bool Gets = false;
	mutable bool glass = false;
	mutable bool Hair = false;
	mutable bool has = false;
	mutable bool hasCloakRoomTicket = false;
	mutable bool important = false;
	mutable bool ITEM = false;
	mutable bool looking = false;
	mutable bool LOST = false;
	mutable bool must = false;
	mutable bool now = false;
	mutable bool of = false;
	mutable bool one = false;
	mutable bool other = false;
	mutable bool places = false;
	mutable bool potential = false;
	mutable bool re = false;
	mutable bool RED = false;
	mutable bool s = false;
	mutable bool SHOE = false;
	mutable bool Someone = false;
	mutable bool speakCzech = false;
	mutable bool The = false;
	mutable bool WRISTBAND = false;
	mutable bool You = false;
	
	void SetGV(UArticyGlobalVariables* GV) const override
	{
		auto gv = Cast<UEclipse_9000GlobalVariables>(GV);
		/** Initialize all GV namespace references (or nullify if we're setting to nullptr) */
		/** Store GVs */
		ActiveGlobals = gv;
	}
	
	UArticyGlobalVariables* GetGV() override
	{
		/** Return active global variables as set by SetGV */
		if(ActiveGlobals.IsValid()) { return ActiveGlobals.Get(); }
		return nullptr;
	}
	
	UClass* GetUserMethodsProviderInterface() override
	{
		return UEclipse_9000MethodsProvider::StaticClass();
	}
	
public:
	
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(push)
	#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
	#endif
	 UEclipse_9000ExpressoScripts() 
	{
		Conditions.Add(-316595917, [&]
		{
			return ConditionOrTrue(
				hasCloakRoomTicket
			);
		});
		Conditions.Add(-524678868, [&]
		{
			return ConditionOrTrue(
				// has Angel's Hair

			);
		});
		Conditions.Add(-232813307, [&]
		{
			return ConditionOrTrue(
				// has Angel's Eye

			);
		});
		Conditions.Add(-1096222416, [&]
		{
			return ConditionOrTrue(
				// speakCzech?

			);
		});
		Conditions.Add(-932506931, [&]
		{
			return ConditionOrTrue(
				talkedTo(1)
			);
		});
		Instructions.Add(-679280213, [&]
		{
			// ITEM: RED WRISTBAND
// Gets you places. You're important now.

		});
		Instructions.Add(-1136287476, [&]
		{
			// ITEM: LOST SHOE
// Someone must be looking for the other one.

		});
		Instructions.Add(-1920013001, [&]
		{
			// ITEM: EMPTY GLASS
// The potential of an empty glass.

		});
	}
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(pop)
	#endif
};
